/**
 * Cellar — nbdev-style cell export identity.
 *
 * A code cell can be marked for export to a generated module (nbdev's `#|export`),
 * recorded as `metadata.cellar.export = true`. The `cellar` namespace is the one
 * clean-on-save preserves, so the flag survives a save byte-for-byte and produces
 * no git noise. Only code cells can be exported (a markdown/SQL cell carries no
 * module source), so converting a cell away from code drops the flag.
 *
 * ELIGIBILITY IS TARGET-AWARE: the export target's extension names the module's
 * LANGUAGE (`.py` or `.mojo`, see `exportTargetLanguage`) and a cell is eligible
 * for it iff the cell's own language matches (`exportLanguageOf`). That is one
 * sentence covering both languages, rather than a `.py` rule with a Mojo
 * exclusion bolted on - see `canExportCell`.
 *
 * Both halves of the app read this identity — the server (`notebook.ts`,
 * `export-py.ts`) and the browser (`Cell.svelte`) — so it lives in one pure,
 * browser-safe module rather than a predicate copied on each side. It is the
 * export counterpart to `importsRole.ts`.
 */

import type { CellMetadata } from '$lib/server/types';
import { isLogicalCellType, isMojoCell } from '$lib/cellLanguage';
import { hasMojoHeader } from '$lib/cellMagic';
import { hasBareNbdevDirective } from '$lib/nbdevDirectives';

/** The minimal cell shape this rule reads (Cell/CellView are assignable). */
type ExportCell =
	| { cell_type?: string; source?: string; metadata?: CellMetadata | null }
	| null
	| undefined;

/**
 * The language a generated module is written in. A notebook names ONE export
 * target, and its extension decides which language that module is - and therefore
 * which cells may go into it.
 */
export type ExportLanguage = 'python' | 'mojo';

/**
 * The module language an export target's path names, or null when the path names
 * no module Cellar can generate.
 *
 * `.py` and `.mojo` only. Both writers stamp the same `#` header (a comment in
 * both languages), so the clobber guard, the idempotent re-export and the
 * "was this generated by Cellar" test carry over unchanged.
 */
export function exportTargetLanguage(target: string | null | undefined): ExportLanguage | null {
	const raw = String(target ?? '').trim();
	if (/\.py$/i.test(raw)) return 'python';
	if (/\.mojo$/i.test(raw)) return 'mojo';
	return null;
}

/**
 * The language of the module source this cell WOULD contribute, or null when it
 * contributes none.
 *
 * Two things make a cell Mojo, and the second is why this is not simply the
 * logical cell type:
 *
 *   - Cellar's own `mojo` cell type (`metadata.cellar.language = 'mojo'`).
 *   - A plain `code` cell whose source opens with a `%%mojo` cell magic - what a
 *     user gets by pasting an example out of Modular's own documentation without
 *     converting the cell's type. Such a cell reads as Python to every type-based
 *     test while its body is Mojo, and it is the LIVE DEFECT this rule closes:
 *     marked for export it had its Mojo body concatenated into a `.py` module
 *     that nbdev commits to git.
 *
 * Deliberately scoped to `%%mojo` and to no other cell magic. A `%%bash` or
 * `%%html` cell is equally not-Python, and exporting one equally produces a module
 * that will not compile - but that is the PRE-EXISTING hazard class
 * `$lib/exportHazard` names and deliberately does not detect (the user's own
 * source, unchanged by the export). Widening this to every magic is a separate
 * decision; claiming a `%%mojo` cell belongs in a `.mojo` module is not, because
 * that module is exactly where its body compiles.
 */
export function exportLanguageOf(cell: ExportCell): ExportLanguage | null {
	if (isMojoCell(cell)) return 'mojo';
	if (!isLogicalCellType(cell, 'code')) return null;
	return hasMojoHeader(cell?.source) ? 'mojo' : 'python';
}

/**
 * MAY this cell carry the export flag for a module of this language? Only a code
 * cell whose own language MATCHES the target's - a markdown/SQL/raw cell has no
 * module source at all, a Mojo cell has no place in a `.py` module, and a Python
 * cell has none in a `.mojo` one.
 *
 * The Python half is `isLogicalCellType(cell, 'code')`, never a bare nbformat
 * `cell_type === 'code'`: a SQL cell IS an nbformat `code` cell tagged
 * `cellar.language='sql'` (see `cellLanguage.ts`), so that test admits one — and
 * its raw SQL would then be concatenated into the generated module, a file nbdev
 * commits to git. It is deliberately the STRICT predicate rather than
 * `logicalCellType(cell) === 'code'`, which maps an nbformat `raw` cell (passed
 * through untouched from an externally-authored notebook) to `code` too.
 *
 * This is the ELIGIBILITY rule, exported so the two SETTERS (`notebook.ts`'s
 * `setCellExports`, MCP's `setCellExport`) test it through the same function
 * `isExportCell` is built from, rather than each re-deriving it from
 * `isLogicalCellType` and agreeing only by coincidence. A cell can then never be
 * marked into a state the exporter ignores.
 *
 * ## Why `lang` is TARGET-AWARE rather than a flat "Mojo is not exportable"
 *
 * Stated as an exclusion, this rule would have to be UNPICKED the moment a
 * `.mojo` target existed. Stated as a match, the `.mojo` export is an ADDITION:
 * the same sentence - a cell is exportable to a target iff its language matches
 * the target's extension - gives both answers, and a third language would inherit
 * it. `exportLanguageOf` is where a language is decided, once.
 *
 * `lang` DEFAULTS to `'python'`, which is the legacy question and byte-for-byte
 * the previous behaviour: every export target that existed before `.mojo` was a
 * `.py` one. Every caller that has a target in scope passes the real value; the
 * one that cannot is `storedExportTarget`'s marked-cell gate, which is about an
 * nbdev `#|default_exp` directive - Python vocabulary - and says so.
 */
export function canExportCell(cell: ExportCell, lang: ExportLanguage = 'python'): boolean {
	return exportLanguageOf(cell) === lang;
}

/**
 * Does this cell's SOURCE carry nbdev's bare `#| export` directive?
 *
 * Read STATICALLY, never by running the cell - a `#|` line is a comment. The
 * scanning rule (leading block only, exact name, `true` as bare) lives in
 * `$lib/nbdevDirectives`, measured against nbdev 3.3.13.
 *
 * ## Only a BARE `#| export`, and only that name
 *
 * A VALUED `#| export other` is deliberately NOT a mark: measured against real
 * nbdev, that exports the cell to a module named `other`, a SECOND module beside
 * the notebook's `default_exp` one. Cellar has exactly one target per notebook, so
 * treating it as a mark would concatenate the cell into the wrong module - the
 * very "resolves plausibly and writes to the wrong file" defect the scout report's
 * §5.2 is about, reached from the cell side instead of the target side.
 *
 * `exporti` / `exports` / `exportd` are each a DIFFERENT directive name, so the
 * exact-name test excludes them with no special case. That is the scoped decision,
 * not an oversight:
 *
 * - `exporti` is module code that is NOT in `__all__`, and `exportd` is docstring
 *   material that is not module code at all. A single boolean cannot say either,
 *   and a wrong guess writes an unwanted public name or a markdown blob into a
 *   file that is committed to git.
 * - `exports` is, MEASURED, module-identical to `export` (both land in the module
 *   and in `__all__`; the difference is purely docs rendering, which Cellar has
 *   no equivalent of). It is left unrecognised anyway because the increment's
 *   scope names it, and widening it is a one-line change wherever that is decided.
 *
 * The cost of not recognising them is stated plainly: a module Cellar generates for
 * such a notebook omits those cells, so a marked cell calling an `exporti` helper
 * yields a module that raises `NameError` on import. That is not a regression -
 * Cellar saw ZERO nbdev marks before - but it is a real limit, and the clobber
 * guard in `export-py.ts` is what stops it damaging an existing nbdev module.
 */
export function hasExportDirective(cell: ExportCell): boolean {
	return hasBareNbdevDirective(cell?.source, 'export');
}

/**
 * Does this cell's own SOURCE own its export mark - i.e. is the cell exported
 * BECAUSE of a `#| export` line Cellar may never write and so may never remove?
 *
 * This is the refusal rule, and it is deliberately `canExportCell(cell) &&
 * hasExportDirective(cell)` in ONE place rather than that pair repeated at each
 * refusing site. The two halves must be the same eligibility the MARK rule applies,
 * because a refusal is a claim about `isExportCell`: a markdown/SQL/raw cell whose
 * source happens to open with `#| export` is NOT exported (the exporter ignores it
 * entirely), so reporting the directive as owning it would refuse to clear a stale
 * flag and tell the caller a cell is in a module it was never in. Every refusing
 * surface asks this - the doc setter, its batch form, the PATCH route through them,
 * MCP's `set_cell_export`, and the row toggle - so the client and the server cannot
 * drift about which cells the source owns.
 */
export function exportDirectiveOwnsCell(cell: ExportCell, lang: ExportLanguage = 'python'): boolean {
	return canExportCell(cell, lang) && hasExportDirective(cell);
}

/**
 * Is this cell marked for export TWICE - by a `#| export` line in its source AND
 * by Cellar's own `metadata.cellar.export` flag?
 *
 * Reachable and ordinary: mark a cell in Cellar, then let nbdev's directive arrive
 * on its source (an agent edit, a pull, a hand edit). It exists because it is what
 * every refusal SENTENCE turns on. `setCellExports` skips a directive-owned cell in
 * BOTH directions - a decision that stands - so in this state the flag cannot be
 * cleared either, and "remove that line to stop exporting it" is FALSE: with the
 * line gone the flag still marks the cell, the toggle still reads ON, and the
 * exporter still writes it. A feature whose premise is that the UI must never lie
 * about what will be exported cannot ship that sentence in this state.
 *
 * So the CONDITION lives here, once, and the three surfaces that carry the sentence
 * each branch on it in their own voice - the shell notice (`LiveNotebook.setExport`),
 * the row toggle's `title` (`Cell.svelte`), and MCP `set_cell_export`'s refusal,
 * which is handed the answer on its refusal record so the server half asks the same
 * question rather than re-deriving it.
 */
export function exportMarkedTwice(cell: ExportCell, lang: ExportLanguage = 'python'): boolean {
	return exportDirectiveOwnsCell(cell, lang) && cell?.metadata?.cellar?.export === true;
}

/**
 * Is this cell marked for export to the `.py` module? Eligible (`canExportCell`)
 * AND marked - by Cellar's own `metadata.cellar.export` flag, or by nbdev's
 * `#| export` directive in the source.
 *
 * ## Which wins, and why the question has no answer to argue about
 *
 * nbdev's own rule is comments-beat-metadata (`fastcore/nbio.py` `_directives_get`)
 * and Cellar's is metadata-first, so the two look like they must be reconciled.
 * For THIS flag they do not, because NEITHER SOURCE CAN EXPRESS A NEGATION:
 * nbdev's `#| export` is presence-only (there is no "not exported" directive), and
 * Cellar's flag is presence-only too - `setCellExports` DELETES the key rather than
 * storing `false`, and this predicate is a strict `=== true`, so an absent flag and
 * a hand-edited `false` already read alike. With no way to say "no", precedence has
 * nothing to decide: comments-win, metadata-win and union are the SAME function on
 * the values that can actually occur. A cell is exported if either says so.
 *
 * That is what makes this settleable without a product call - the disagreement the
 * two designs appear to have is not reachable.
 *
 * ## The UI consequence, which IS a decision
 *
 * Marking stays metadata-only: toggling export in Cellar must never write a `#|`
 * line into the user's source. Source is code the kernel runs and git diffs, while
 * `metadata.cellar` is the namespace clean-on-save preserves byte-for-byte - the
 * whole reason this flag lives there. So a cell the DIRECTIVE marks cannot be
 * unmarked from Cellar at all: `setCellExports` refuses it and the row toggle shows
 * ON while staying LIVE rather than going `disabled` - a disabled button gets no
 * pointer events, so its `title` could never be hovered and the one thing the user
 * needs (which line to remove) would be unreachable. Clicking it declines on the
 * shell's notice line instead, the same live-control-that-explains-itself stance the
 * Databricks card takes. Clearing the metadata half instead would leave the cell
 * exported with the toggle bouncing back to ON, which is exactly the lie this is
 * written to avoid.
 *
 * Being the one identity every surface reads (`export-py.ts` builds the module
 * from it, `Cell.svelte` draws the badge from it, the agent map reports it),
 * keeping the eligibility half here is what makes a stale or hand-edited flag on
 * a markdown/SQL/raw cell inert everywhere rather than only at whichever setter
 * last remembered to check.
 */
export function isExportCell(cell: ExportCell, lang: ExportLanguage = 'python'): boolean {
	if (!canExportCell(cell, lang)) return false;
	return cell?.metadata?.cellar?.export === true || hasExportDirective(cell);
}

/**
 * Does this cell carry Cellar's own export FLAG while being INELIGIBLE for the
 * module the notebook currently targets?
 *
 * Reachable and ordinary: mark some Python cells for a `.py` target, then point
 * the target at a `.mojo` one (or the reverse). Nothing rewrites the notebook -
 * silently editing the user's committed `.ipynb` because a setting moved is worse
 * than the stale flag - so `metadata.cellar.export` stays where it is, `isExportCell`
 * reads false, the cell contributes to no module and the export count drops.
 *
 * It exists because a row toggle that is merely ABSENT there leaves that flag with
 * no surface at all: invisible in the notebook, still in the committed file, and
 * clearable only by pointing the target back. So the toggle is RENDERED for such a
 * cell - greyed, saying why, and still able to clear the flag, which the server
 * allows (`setCellExports` gates only MARKING on eligibility, never unmarking).
 *
 * Deliberately the FLAG alone, never `hasExportDirective`: an `#| export` line is
 * the cell's own source, which Cellar may not write and so may not remove, and it
 * is Python vocabulary that says nothing about a `.mojo` target. There is nothing
 * for a toggle to clear.
 */
export function exportMarkStranded(cell: ExportCell, lang: ExportLanguage = 'python'): boolean {
	return cell?.metadata?.cellar?.export === true && !canExportCell(cell, lang);
}

/** Count of cells currently marked for export to a module of this language. */
export function exportCellCount(
	cells: readonly ExportCell[] | null | undefined,
	lang: ExportLanguage = 'python'
): number {
	return (cells ?? []).filter((c) => isExportCell(c, lang)).length;
}
