import { chromium } from '@playwright/test';
const [url, ws, out] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs = [];
p.on('pageerror', e => errs.push(String(e.message ?? e)));
p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto(`${url}/?ws=${encodeURIComponent(ws)}`);
await p.locator('[data-testid="tree-file"][data-path="tools.ipynb"]').click();
const cell = p.locator('[data-testid="cell"][data-cell-id="chatlive1"]');
await cell.waitFor({ timeout: 30000 });
await cell.getByTestId('run').click();
const reply = cell.getByTestId('output-markdown');
await reply.waitFor({ timeout: 120000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: out, fullPage: false });
console.log('--- rendered reply text ---');
console.log(await reply.innerText());
console.log('--- blockquotes:', await reply.locator('blockquote').count(), 'code spans:', await reply.locator('blockquote code').count());
console.log('--- page errors:', JSON.stringify(errs));
await b.close();
