/**
 * Cellar — nbdev-style selective export to a `.py` module.
 *
 * A notebook can name a target `.py` module (`notebook.metadata.cellar.export_target`,
 * nbdev's `#|default_exp`) and mark individual code cells for export
 * (`metadata.cellar.export`, nbdev's `#|export`). The target's path may be
 * expressed relative to the workspace (the default - and what an ABSENT
 * `metadata.cellar.export_base` permanently means, so every pre-base notebook
 * resolves unchanged), to the notebook's own folder, or to the notebook's git
 * root (see `$lib/exportTarget` and `resolveExportTarget` below). This module
 * reads the marked cells IN ORDER and writes a clean Python module: a "do not
 * edit" header, a best-effort `__all__`, and the exported sources concatenated.
 *
 * This is deliberately DISTINCT from the jupytext `.py` export in
 * `jupytext-actions.ts`: that mirrors the WHOLE notebook as a text notebook (cell
 * markers, every cell). This writes a lean module of only the marked cells — the
 * nbdev "library from notebook" model, where the generated module is committed to
 * git (so it is NOT gitignored).
 *
 * Output is deterministic and idempotent: identical marked content yields a
 * byte-identical file, so re-exporting produces no git diff.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, basename, relative, resolve, sep } from 'node:path';
import { resolveInWorkspace, workspaceRoot } from './fstree';
import { gitRootOf } from './git';
import { logicalLines, stripComments, splitSimpleStatements } from './imports';
import { isExportCell } from '../exportRole';
import { nbdevDirective, nbdevDirectiveOutsideBlock } from '../nbdevDirectives';
import { nbdevLibPath } from './nbdev';
import { isExportBase, type ExportBase } from '../exportTarget';
import { futureImportJoinedHazard, type ExportHazard } from '../exportHazard';
import type { Cell, NotebookDoc } from './types';

/** The header stamped at the top of every generated module. */
const HEADER = '# AUTOGENERATED BY CELLAR! DO NOT EDIT!';

export interface ExportResult {
	/** true if the file was (re)written; false if unchanged / nothing to do. */
	written: boolean;
	/**
	 * The RESOLVED workspace-relative target path (whatever base it was expressed
	 * under), or null when no target is configured. On the `no-cells` early return
	 * of a target that cannot resolve, the stored form - the only spelling in hand.
	 */
	target: string | null;
	/** number of cells exported. */
	count: number;
	/**
	 * why nothing was written, when `written` is false.
	 *
	 * `foreign-module` is the clobber guard declining: a file Cellar did not generate
	 * already occupies the target, so there is nothing it may legitimately write. It
	 * is an OUTCOME rather than an error because it is the STEADY STATE of an
	 * established nbdev repo - the library module carries nbdev's own header, and
	 * every save would otherwise raise and leave `lastExportError` set forever.
	 */
	reason?: 'no-target' | 'no-cells' | 'unchanged' | 'foreign-module';
	/**
	 * Constructs in the marked cells that make the generated module uncompilable
	 * (`$lib/exportHazard`). Empty on every ordinary export, and empty for
	 * `no-target`/`no-cells`, where no module describes those cells at all.
	 *
	 * Carried on `unchanged` too, and that is the point rather than an edge case:
	 * the broken module is still ON DISK, so a re-export that writes nothing must
	 * not report the plain success the first one was corrected out of. Empty for
	 * `foreign-module` for the SAME reason as `no-cells`: the file at the target is
	 * not one Cellar wrote, so nothing on disk describes these marks.
	 *
	 * A POSITIVE finding, never a compile verdict - the class is wider than what
	 * is detected. `$lib/exportHazard`'s header states the measured boundary; no
	 * caller may word an empty list as "the module compiles".
	 */
	hazards: ExportHazard[];
}

/**
 * Best-effort top-level names for `__all__`, from a single cell's source:
 * top-level `def`/`class` and simple top-level assignments (`X = …`,
 * `X: T = …`, `A, B = …`). Names starting with `_` are omitted (nbdev/Python
 * convention: private). Order is preserved; the caller dedupes across cells.
 *
 * Uses the imports tokenizer's `logicalLines` so `=`/`def`/`class` inside a
 * string or a nested (indented) scope are never mistaken for a definition.
 * Known limits (documented, acceptable for a best-effort `__all__`): augmented
 * assignments (`X += …`), `del`, and dynamically-created names are invisible.
 */
export function topLevelNames(source: string): string[] {
	const names: string[] = [];
	for (const line of logicalLines(source)) {
		if (line.indent !== 0) continue; // only module-level statements define exports
		const head = line.raw.replace(/^\s+/, '');
		// def / class (including `async def`)
		const dc = head.match(/^(?:async\s+)?(?:def|class)\s+([A-Za-z_]\w*)/);
		if (dc) {
			names.push(dc[1]);
			continue;
		}
		// annotated single assignment: `NAME: T = …`
		const ann = head.match(/^([A-Za-z_]\w*)\s*:\s*[^=]+=(?!=)/);
		if (ann) {
			names.push(ann[1]);
			continue;
		}
		// plain assignment (single or tuple): LHS before the first real `=`.
		const eq = head.match(/^([^=]+?)=(?!=)/);
		if (eq) {
			const lhs = eq[1].trim();
			// Only accept an LHS that is purely comma-separated identifiers, so
			// `a == b`, `a[i] = …`, `a.b = …`, `x <= y` never leak in.
			if (/^[A-Za-z_]\w*(\s*,\s*[A-Za-z_]\w*)*$/.test(lhs)) {
				for (const n of lhs.split(',')) names.push(n.trim());
			}
		}
	}
	// Drop private names, dedupe, preserve first-seen order.
	const seen = new Set<string>();
	const out: string[] = [];
	for (const n of names) {
		if (n.startsWith('_') || seen.has(n)) continue;
		seen.add(n);
		out.push(n);
	}
	return out;
}

/** Render a Python list literal for `__all__` (deterministic, single-quoted). */
function renderAll(names: string[]): string {
	if (!names.length) return '__all__ = []';
	return `__all__ = [${names.map((n) => `'${n}'`).join(', ')}]`;
}

/**
 * A module-level `from __future__ import …` statement, as a whole logical line.
 *
 * The tail is `\b`, NOT `\s+\S`: `from __future__ import(annotations)` needs no
 * space before the parenthesis and Python compiles it, so requiring one left that
 * spelling unhoisted and emitted the uncompilable module this exists to remove.
 * A word boundary still rejects `from __future__ importannotations`.
 */
const FUTURE_RE = /^from\s+__future__\s+import\b/;

/**
 * Lift every module-level `from __future__ import …` out of the exported sources.
 *
 * Python requires a future statement to precede every other statement in the
 * module, but `generateModule` emits `__all__` first — so an exported cell
 * carrying one produced a module **Python refuses to compile** while the export
 * reported `written: true`. Cellar's own imports-cell renderer deliberately puts
 * `__future__` first inside that cell (`imports.ts`), so marking the imports cell
 * for export is the likeliest way to hit it.
 *
 * Hoisting is unconditionally semantics-preserving here: a future statement is a
 * compile-time directive whose effect is the whole module, and the `indent !== 0`
 * filter means only genuinely module-level ones move. That makes this STRICTLY
 * more correct than nbdev's own `_last_future` (`maker.py`), which hoists whole
 * CELLS up to the last one containing a future import — so nbdev still emits an
 * uncompilable module when a future import trails real code, where this does not.
 *
 * `logicalLines` is what makes it safe: a `from __future__ …` inside a string or a
 * nested scope is never a logical line at indent 0, and a bracket-continued import
 * is ONE logical line, so it moves whole.
 *
 * WHAT THE `;` RULE IS, and it is a rule about JOINING, not about the character.
 * The line's CODE is split by `splitSimpleStatements` (`imports.ts`, the one
 * top-level `;` splitter - never a second `includes(';')` scan), and only a line
 * that really carries a SECOND statement is left alone. So a bare trailing
 * semicolon (`from __future__ import annotations;`) IS hoisted - there is no rider
 * to reorder, so refusing it closed nothing and emitted the uncompilable module
 * this exists to remove - and so is a `;` sitting in a trailing comment, which
 * `stripComments` has already dropped before the split.
 *
 * A genuinely semicolon-JOINED statement (`from __future__ import annotations;
 * x = 1`) is still left in place, because hoisting it would reorder the statement
 * riding with it and relocating a user's code is out of scope for an export. What
 * is NOT left in place is the report: such a line is recorded as a HAZARD
 * (`$lib/exportHazard`), rides out on `ExportResult.hazards`, and every surface
 * that reports the export says so instead of plain success. The module really is
 * still written - see `exportNotebookToPy`'s header for why writing beats
 * refusing here - and it really will not import, and the user is told which line
 * to change. Detecting is done HERE, in the same walk that decides the hoist, so
 * the hoist rule and the hazard rule cannot drift into disagreeing about which
 * lines Cellar declines to move.
 *
 * The hazard fires on a joined line carrying a `__future__` import in ANY
 * position, not only first: `x = 1; from __future__ import annotations` does not
 * compile even standalone, so a module built from it cannot either, and reporting
 * it is strictly better than the silence it used to get.
 *
 * Returns the deduped hoisted statements, the sources with them spliced out, and
 * the hazards found on the way.
 */
function liftFutureImports(sources: string[]): {
	future: string[];
	body: string[];
	hazards: ExportHazard[];
} {
	const future: string[] = [];
	const hazards: ExportHazard[] = [];
	const seen = new Set<string>();
	const body = sources.map((src) => {
		if (!src.includes('__future__')) return src; // cheap pre-check; the common case
		const cuts: Array<[number, number]> = [];
		for (const line of logicalLines(src)) {
			if (line.indent !== 0) continue; // only a module-level future statement moves
			// The CODE of the line: comments dropped, continuations folded, strings kept.
			const code = stripComments(line.raw).replace(/\s+/g, ' ').trim();
			const parts = splitSimpleStatements(code);
			if (parts.length !== 1) {
				// A line carrying a second statement: never hoisted, and - when one of
				// those statements IS a future import - never reported as a clean export.
				// Quoted back from `line.raw` (what the user TYPED, trailing comment and
				// all) rather than from `code`, so the message names a line they can find
				// on screen; `quoteStatement` folds and bounds it.
				if (parts.some((part) => FUTURE_RE.test(part))) hazards.push(futureImportJoinedHazard(line.raw));
				continue;
			}
			if (!FUTURE_RE.test(parts[0])) continue;
			if (!seen.has(parts[0])) {
				seen.add(parts[0]); // dedupe on the statement, so a comment or a trailing `;` is not a new one
				future.push(line.raw.replace(/\s+$/, '')); // hoisted verbatim, comment and all
			}
			cuts.push([line.start, line.end]);
		}
		if (!cuts.length) return src;
		return spliceLines(src, cuts);
	});
	return { future, body, hazards };
}

/**
 * Every compile hazard in a set of exported sources - the ONE rule, shared by the
 * exporter, the notebook view the export bar renders, and the agent surface, so
 * none of them can describe the same module differently.
 *
 * It runs `liftFutureImports` rather than a second scan of its own: the hazard is
 * defined as "a line the hoist declines to move", which only the hoist can answer.
 * The discarded body is the cost of that, and it is trivial - a pure walk behind a
 * `__future__` substring pre-check, over marked cells only.
 */
export function exportHazards(sources: string[]): ExportHazard[] {
	return liftFutureImports(sources).hazards;
}

/**
 * A DOCUMENT's compile hazards: what the module its marks describe would carry.
 *
 * Gated on a target being CONFIGURED, because a hazard is a statement about a
 * module - with no target there is no module for it to be about, and warning
 * there would be noise on a notebook that exports nothing. A target that cannot
 * RESOLVE is deliberately not gated out: the marks still describe that module,
 * and the surfaces order the two warnings themselves.
 *
 * `resolved` is an optional already-resolved target, so a caller that has one in
 * hand (`exportTargetView`, which resolves for its own fields) does not pay a
 * second resolution - the `canonicalWorkspace()` optional-argument idiom. A lone
 * call resolves once, itself.
 */
export function docExportHazards(
	doc: NotebookDoc,
	resolved: ResolvedExportTarget | null = resolveExportTarget(doc)
): ExportHazard[] {
	if (!resolved) return [];
	const exported = doc.cells.filter((c: Cell) => isExportCell(c)).map((c) => c.source);
	if (!exported.length) return [];
	const hazards = exportHazards(exported);
	// The foreign-module question is asked LAST in code and FIRST in meaning: over a
	// target the clobber guard declines there is no module of ours and never will be,
	// so a hazard sentence describes a file that cannot exist - MCP's `moduleHazard`
	// says outright that `<target>` WAS written, and the export bar's own claim about
	// the module these marks describe is equally beside the point when no export can
	// land. Ordering it here is what keeps that bar and `moduleHazard` (which reads
	// this same function through `exportHazardsFor`) from describing one document
	// differently - the drift the shared-rule convention exists to prevent.
	// `exportNotebookToPy` already zeroes its own hazards on that branch, for the
	// same reason.
	//
	// Asked only once there IS a hazard to suppress, so the file read costs nothing
	// on the ordinary `getNotebook` / persist path.
	if (!hazards.length) return [];
	if (resolved.ok && foreignModuleAt(resolved.target)) return [];
	return hazards;
}

/**
 * Cut `[start, end)` spans out of `src` and tidy the seams they leave behind.
 *
 * Removing a whole line leaves the newlines that closed around it, so a naive
 * splice turns "future import, blank line, code" into a residue that OPENS with a
 * blank line - which `generateModule` then joins with its own blank-line separator
 * and emits a double blank line, contradicting its documented "single blank line
 * between blocks, no incidental whitespace" contract. Two passes address that, and
 * both are deliberately narrower than "normalize the blank lines", because the
 * newlines a cut did NOT create are the user's own text.
 *
 * Seams are tidied RIGHT TO LEFT and only ever by removing characters at or after
 * the seam, so an earlier seam's recorded offset is never invalidated (the same
 * rule `extractTopLevelImports` follows for the same reason). That is exactly why
 * the collapse is one-sided and its LIMIT is stated rather than glossed: only the
 * newline run FOLLOWING a seam can be shortened, so a seam whose PRECEDING run was
 * already more than one blank line keeps it (`A = 1\n\n\n\n<cut>\nB = 2` stays
 * `A = 1\n\n\n\nB = 2`). What it does guarantee is the case this exists for: a cut
 * whose own newline lands next to at most one authored blank line contributes none
 * of its own.
 *
 * The leading strip is likewise blunt and unconditional once ANY cut landed: it
 * removes every blank line at the top of the residue, including ones the user wrote
 * that no cut produced. Kept that way because it is the shape that actually occurs
 * (a `__future__` import is legal only at the top of a module, so a cut is almost
 * always the thing that opened the gap) and because leading blank lines carry no
 * meaning at module level. Both residuals are cosmetic only - the contracts that
 * matter (deterministic, idempotent, byte-identical re-export, and the future block
 * landing above `__all__`) are unaffected either way.
 */
function spliceLines(src: string, cuts: Array<[number, number]>): string {
	let out = '';
	const seams: number[] = [];
	let at = 0;
	for (const [s, e] of cuts) {
		out += src.slice(at, s);
		seams.push(out.length);
		at = e;
	}
	out += src.slice(at);
	for (let i = seams.length - 1; i >= 0; i--) {
		const p = seams[i];
		let before = 0;
		while (p - before - 1 >= 0 && out[p - before - 1] === '\n') before++;
		let after = 0;
		while (p + after < out.length && out[p + after] === '\n') after++;
		const excess = before + after - 2;
		if (excess > 0) out = out.slice(0, p) + '\n'.repeat(Math.max(0, after - excess)) + out.slice(p + after);
	}
	return out.replace(/^(?:[ \t]*\n)+/, ''); // every leading blank line goes, once any cut landed
}

/**
 * Build the full module text from the exported cells (already filtered + in
 * document order). Deterministic: a trailing newline, single blank line between
 * blocks, no incidental whitespace, so re-exporting identical content is a
 * byte-for-byte no-op.
 *
 * Module-level `__future__` imports are hoisted above `__all__` (see
 * `liftFutureImports`); a comment is the only thing Python allows before one, and
 * the header is comments, so the emitted order compiles.
 */
export function generateModule(exportedSources: string[], sourceName: string): string {
	const { future, body: bodySources } = liftFutureImports(exportedSources);
	const allNames: string[] = [];
	const seen = new Set<string>();
	for (const src of bodySources) {
		for (const n of topLevelNames(src)) {
			if (!seen.has(n)) {
				seen.add(n);
				allNames.push(n);
			}
		}
	}
	const blocks: string[] = [`${HEADER}\n# Source notebook: ${sourceName}`];
	if (future.length) blocks.push(future.join('\n'));
	blocks.push(renderAll(allNames));
	for (const src of bodySources) {
		const trimmed = src.replace(/\s+$/, ''); // drop trailing blank lines within a cell
		if (trimmed) blocks.push(trimmed);
	}
	return blocks.join('\n\n') + '\n';
}

/**
 * A configured export target, resolved through its BASE (`$lib/exportTarget`).
 *
 * `ok:true` carries the stored form (`base` + `path`), the workspace-relative
 * `target` every consumer of "where do the marks land" reads, and the absolute
 * `abs` the exporter writes to. `ok:false` means a target IS configured but
 * cannot resolve - a different fact from "no target", and one that must never
 * be collapsed into it: `moduleWarning` and the UI both key off a null target
 * as "nothing configured", so an unresolvable one has to keep its own shape.
 */
export type ResolvedExportTarget =
	| { ok: true; base: ExportBase; path: string; source: 'metadata' | 'default_exp'; target: string; abs: string }
	| { ok: false; base: string; path: string; source: 'metadata' | 'default_exp'; error: string };

/**
 * The STORED export target for a doc: the notebook-level `export_target` (with
 * its recorded `export_base`; absent = workspace, the permanent legacy meaning),
 * or a `#|default_exp <module>` directive found in any cell (nbdev familiarity;
 * the UI field is the primary mechanism). Returns null when neither is present.
 *
 * A directive target never reads `export_base`, which is a property of the
 * notebook-level SETTING alone: a directive lives in a cell, so pairing it with
 * notebook-level base metadata would make one cell's text mean different files
 * depending on a setting no setter can see from the cell. Its root is nbdev's
 * own - the project's `lib_path` where there is one, else the workspace, exactly
 * as before (see `directiveBase`).
 *
 * The directive is read through the SHARED `$lib/nbdevDirectives` scanner, which
 * applies nbdev's real rule (leading block only), not a `/m` regex over the whole
 * source: a `#|default_exp` sitting after code, after a plain comment, or inside a
 * triple-quoted string is NOT a directive to nbdev, so honouring it was the
 * "half-speaks nbdev" defect - a target resolved from text nbdev ignores.
 *
 * The directive scan is guarded by a `includes('default_exp')` substring test
 * (`dataframeHtml.ts`'s `/dataframe/i` pre-check, same reason): this is the ONE
 * resolution rule the exporter AND the agent map read, and the map short-circuits
 * only when a notebook-level target IS set — so the COMMON case, a notebook with
 * no export configured at all, would otherwise run the shared scanner over every
 * code cell on the most frequently called agent read tool.
 *
 * The guard belongs HERE and deliberately NOT inside the scanner, which carries
 * none: this caller sweeps EVERY cell before it may conclude "no target", so a
 * cheap per-cell reject pays for itself. `nbdevDirectives.ts`'s header has the
 * measurement and the other half of that reasoning.
 */
function storedExportTarget(
	doc: NotebookDoc
): { path: string; base: string; source: 'metadata' | 'default_exp'; error?: string } | null {
	const explicit = doc.metadata?.cellar?.export_target;
	if (typeof explicit === 'string' && explicit.trim()) {
		const rawBase = doc.metadata?.cellar?.export_base;
		const base = typeof rawBase === 'string' && rawBase.trim() ? rawBase.trim() : 'workspace';
		return { path: explicit.trim(), base, source: 'metadata' };
	}
	// The value of a `#|default_exp` line this document carries that nbdev IGNORES
	// (it sits outside its cell's leading directive block). Recorded lazily, INSIDE
	// the loop that is already here, so the ordinary paths - a target that resolves,
	// and the far commoner notebook with no export configured at all - pay nothing
	// for it: it is read only for a cell that already passed the `includes` guard
	// AND produced no usable directive.
	let ignored: string | null = null;
	for (const c of doc.cells) {
		if (c.cell_type !== 'code' || !c.source.includes('default_exp')) continue;
		// The scanner reports the RAW remainder of the directive line, because that is
		// what fastcore's own value is (a trailing `# comment` is kept, verified by the
		// committed differential). A module NAME is one token, so it is bounded HERE
		// rather than in the shared scanner - unbounded, `#| default_exp core # note`
		// resolved to a file literally called `core # note.py`.
		const mod = nbdevDirective(c.source, 'default_exp')?.trim().split(/\s+/)[0];
		if (!mod) {
			if (ignored === null) ignored = nbdevDirectiveOutsideBlock(c.source, 'default_exp');
			continue;
		}
		// nbdev writes a dotted module path (`pkg.utils`); map it to a file path.
		const rel = mod.endsWith('.py') ? mod : mod.replace(/\./g, '/') + '.py';
		return { ...directiveBase(rel), source: 'default_exp' };
	}
	// Nothing resolved, and the notebook holds a `#|default_exp` line nbdev ignores.
	// The RULE is untouched (it stays ignored); what changes is that the drop stops
	// being SILENT - see `misplacedDefaultExpError` for the harm, and for why the
	// report needs a MARKED cell before it may speak.
	if (ignored !== null && doc.cells.some((c: Cell) => isExportCell(c)))
		return { path: '', base: 'workspace', source: 'default_exp', error: misplacedDefaultExpError(ignored) };
	return null;
}

/**
 * Why a `#|default_exp` line this notebook carries generates no module.
 *
 * Reading it would be the "half-speaks nbdev" defect (a target resolved from text
 * nbdev ignores, written to a file nbdev would never write), so the leading-block
 * rule stands. But the previous scan was a `/m` regex over the whole source and DID
 * honour such a line, so a notebook that used to generate a committed module now
 * generates none - and with no error and no target the export bar reads exactly
 * like a notebook that never configured one, while the module on disk quietly goes
 * stale. So the ignored line is reported through the EXISTING `exportResolveError`
 * channel: same field, same surfaces, no new UI.
 *
 * It names the CAUSE (the line is not in its cell's leading directive block), that
 * nbdev ignores it there too (so "fixing" Cellar is not the answer), and both ways
 * out.
 *
 * NARROWED to a notebook with at least one export-MARKED cell, because that is the
 * whole of the harm: the marks describe a module, and it is now landing nowhere.
 * Without that gate the message is standing chrome on the always-visible export bar
 * of a notebook that never asked for a module at all - a tutorial DEMONSTRATING
 * nbdev's directives, or a line quoted inside a docstring - asserting "no module is
 * being generated" about one nobody wanted. Under-reporting is the safe direction
 * for a notice (`server/nbdev.ts` says so for the sibling nbdev warning), and a
 * notice users learn to ignore protects nothing. The gate belongs to the REPORT
 * alone: the leading-block RULE is not widened or weakened by it, and a marked
 * notebook still resolves to nothing exactly as it did.
 */
function misplacedDefaultExpError(value: string): string {
	const mod = value.trim().split(/\s+/)[0];
	return `#|default_exp${mod ? ` ${mod}` : ''} is not in its cell's LEADING directive block - it sits after code, after a plain comment, or inside a string, and nbdev ignores a directive there, so Cellar does too: no module is being generated. Move the line to the very top of its cell (above any code or plain comment), or set an explicit export target instead.`;
}

/**
 * The stored FORM for a `#|default_exp` module file, measured from the right root.
 *
 * In an nbdev project that root is the project's `lib_path`, so the reported path
 * is the module RE-EXPRESSED workspace-relative and the base stays `workspace` -
 * which keeps the type's own invariant literally true (`path` measured from `base`
 * yields `target`), keeps every consumer correct without widening the persisted
 * `ExportBase` vocabulary the UI select is built from, and leaves the name `nbdev`
 * free for the fourth PERSISTED base the scout report's section 6.1 proposes. The
 * derivation is the same KIND this branch always did - a dotted module is not a
 * stored path either - just measured from the root nbdev actually uses.
 *
 * Outside an nbdev project the answer is byte-for-byte what it always was:
 * workspace-relative, no filesystem work beyond the detection, so every existing
 * non-nbdev notebook writes exactly where it did.
 *
 * A lib_path that cannot be READ carries the refusal out as `error` rather than
 * degrading - see `nbdevLibPath`. A lib_path OUTSIDE the workspace needs no special
 * case: the re-expression comes back with `../`, and `resolveExportTarget`'s
 * existing containment guard refuses it with the message it already has.
 */
function directiveBase(rel: string): { path: string; base: string; error?: string } {
	let lib: ReturnType<typeof nbdevLibPath>;
	try {
		lib = nbdevLibPath();
	} catch {
		lib = null; // detection must never break a read; fall back to today's behavior
	}
	if (!lib) return { path: rel, base: 'workspace' };
	if (!lib.ok)
		return {
			path: rel,
			base: 'workspace',
			error: `this is an nbdev project (${lib.configPath}), so #|default_exp ${rel.replace(/\.py$/, '').replace(/\//g, '.')} names a module under its lib_path - but ${lib.reason}, so Cellar cannot tell where that module belongs. Set an explicit export target instead, or fix the config.`
		};
	let ws: string;
	try {
		ws = resolve(workspaceRoot());
	} catch {
		return { path: rel, base: 'workspace' };
	}
	const inWorkspace = relative(ws, resolve(lib.libPath, rel)).split(sep).join('/');
	try {
		resolveInWorkspace(inWorkspace);
	} catch {
		// The COMMON real nbdev layout: Cellar opened in `nbs/` while `lib_path` is a
		// sibling, so the module belongs OUTSIDE the workspace. Refusing is the
		// containment rule holding, and it is strictly better than the pre-fix stray
		// `nbs/core.py` nbdev knows nothing about - but the generic guard's "path
		// escapes workspace" says nothing a user can act on, so this names the layout
		// and both ways out.
		return {
			path: inWorkspace,
			base: 'workspace',
			error: `#|default_exp ${rel.replace(/\.py$/, '').replace(/\//g, '.')} names a module in this nbdev project's lib_path (${lib.libPath}), which is OUTSIDE the workspace Cellar is serving - a module can only be written inside it. Open Cellar at the project root (${dirname(lib.configPath)}) instead, or set an explicit export target inside the workspace.`
		};
	}
	return { path: inWorkspace, base: 'workspace' };
}

/**
 * Resolve a doc's export target through its base, or null when none is
 * configured.
 *
 * The `workspace` branch is byte-for-byte the legacy behavior: the stored form
 * IS the workspace-relative target (no path math, no filesystem), so every
 * notebook written before bases existed keeps resolving to the identical file.
 * The `notebook` and `git` branches resolve the stored form against their base
 * directory and then re-express it workspace-relative - and BOTH still pass the
 * SAME `resolveInWorkspace` guard, so a base is a way to EXPRESS a path, never
 * an escape hatch: a resolution landing outside the workspace is refused here
 * exactly as the setter refuses it at store time.
 *
 * The git root is the repository enclosing the NOTEBOOK (`gitRootOf`, an upward
 * `.git` walk from the notebook's own directory - deliberately not the code
 * root, which may be an external worktree and governs the kernel, not the
 * notebook file). That root may sit ABOVE the workspace (`cd repo/analysis &&
 * cellar`), which is fine: only the RESOLVED module must land inside the
 * workspace. A notebook with no enclosing repository is a first-class
 * `ok:false`, and so is an unknown `export_base` value (a hand-edit): failing
 * closed beats silently reading it as workspace-relative and writing a module
 * to a path nobody chose.
 */
export function resolveExportTarget(doc: NotebookDoc): ResolvedExportTarget | null {
	const stored = storedExportTarget(doc);
	if (!stored) return null;
	const { path, base, source } = stored;
	// A directive whose ROOT could not be determined (an nbdev project Cellar cannot
	// read `lib_path` from). Refuse rather than degrade to workspace-relative: that
	// is the stray-module-at-the-workspace-root write this whole branch exists to
	// stop. An explicit `export_target` is unaffected and is the escape hatch.
	if (stored.error) return { ok: false, base, path, source, error: stored.error };
	if (!isExportBase(base)) {
		return {
			ok: false,
			base,
			path,
			source,
			error: `unknown export base ${JSON.stringify(base)}: expected "notebook" or "git" (or no base at all, which means workspace-relative)`
		};
	}
	if (base === 'workspace') {
		try {
			return { ok: true, base, path, source, target: path, abs: resolveInWorkspace(path) };
		} catch (err) {
			// e.g. a hand-edited legacy target escaping the workspace: still "configured
			// but unresolvable", never a throw - the map reads this on every call.
			return { ok: false, base, path, source, error: String((err as Error)?.message ?? err) };
		}
	}
	let baseDir: string;
	if (base === 'notebook') {
		baseDir = dirname(doc.path);
	} else {
		const root = gitRootOf(dirname(doc.path));
		if (!root) {
			return {
				ok: false,
				base,
				path,
				source,
				error: 'the export base is the git root, but this notebook is not inside a git repository - pick another base, or initialize a repository'
			};
		}
		baseDir = root;
	}
	let abs: string;
	try {
		abs = resolveInWorkspace(resolve(baseDir, path));
	} catch {
		return {
			ok: false,
			base,
			path,
			source,
			error: `export target ${path} (relative to the ${base === 'git' ? "notebook's git root" : "notebook's folder"}) resolves outside the workspace - the module can only be written inside the workspace`
		};
	}
	return { ok: true, base, path, source, target: relative(resolve(workspaceRoot()), abs).split(sep).join('/'), abs };
}

/**
 * Generate the `.py` module for a notebook document. Writes only when a target is
 * configured AND at least one code cell is marked for export AND the generated
 * text differs from what is already on disk (so an unchanged re-export touches
 * nothing — no mtime churn, no git diff). The write is path-guarded to the
 * workspace and creates parent directories as needed.
 *
 * Never throws for the "nothing to do" cases (no target / no marked cells): two
 * of its three explicit callers regenerate as a CONSEQUENCE of naming the target
 * or the cells (`setExportTarget`, `setCellExports`), so an absent target must not
 * break the notebook write they just made. A bad target path (escapes the
 * workspace) still throws — that is a real error the manual button surfaces to the
 * user.
 *
 * It also REFUSES to overwrite a file it did not generate. The write is a
 * whole-file replacement, so a target naming an ordinary source file would destroy
 * it — and while `setExportTarget` refuses a non-`.py` path, a `#|default_exp`
 * directive resolves straight to a path here without passing that setter, and a
 * `.py` path may perfectly well be a hand-written module. Every generated module
 * opens with `HEADER`, so testing the file already on disk for it rejects nothing
 * Cellar wrote.
 *
 * The two shapes that guard refuses are DIFFERENT FACTS and are reported
 * differently, which is the point rather than an inconsistency:
 *
 *   - a file PROVABLY not ours (it has content and does not open with `HEADER`)
 *     returns `{written:false, reason:'foreign-module'}` and records NOTHING. It is
 *     an outcome, not an error: it is the steady state of an established nbdev repo,
 *     whose module carries nbdev's own header, so there is nothing Cellar could
 *     legitimately write there and no export ever will.
 *   - a file that cannot be READ was verified as nothing at all, so it still THROWS
 *     - the manual button surfaces that directly and the two consequential callers
 *     record it as `lastExportError` (never breaking the notebook write).
 *
 * An EMPTY file (zero bytes, or whitespace only) is overwritten, not refused: the
 * guard exists to protect CONTENT, and there is none. Pre-creating the module
 * (`touch utils.py`, or the explorer's "New file") before naming the target is an
 * ordinary workflow, and refusing it stopped the module regenerating through a
 * path no UI surface reads.
 *
 * A module the marked cells make UNCOMPILABLE is WRITTEN, and REPORTED
 * (`ExportResult.hazards`) - it is never a refusal, and the choice is deliberate:
 *
 *   1. A refusal degrades SILENTLY on the paths that matter. Two of the three
 *      explicit callers (`setExportTarget`, `setCellExports`) regenerate
 *      best-effort - a throw is recorded on the doc, and that record reaches only
 *      the agent surface. Refusing would leave the PREVIOUS, compilable module on
 *      disk, quietly stale, while the marks moved on: the user's edits would
 *      simply appear to have no effect. A module that fails `import` with Python's
 *      own `SyntaxError` naming `__future__` is loud; a stale one that imports
 *      fine is the more deceptive outcome.
 *   2. It punishes the wrong scope. The hazard is one line in one cell, and the
 *      module may hold a dozen other exported cells; discarding all of them for it
 *      breaks the module/notebook lockstep every other guard here protects.
 *   3. The defect was the REPORT, not the write - Cellar saying "written" about a
 *      file that cannot be imported. Fixing the report closes it; refusing the
 *      write is a second, larger behavior change answering a different question.
 *
 * The hazards ride on EVERY result that describes a module (`written` and
 * `unchanged` alike - an unchanged re-export leaves the broken bytes on disk), and
 * they are a POSITIVE finding, never a compile verdict: see `$lib/exportHazard`
 * for the measured boundary of what is and is not detected.
 */
export function exportNotebookToPy(doc: NotebookDoc): ExportResult {
	const info = resolveExportTarget(doc);
	if (!info) return { written: false, target: null, count: 0, reason: 'no-target', hazards: [] };

	// The nothing-to-do contract holds even over an unresolvable target: with no
	// cell marked there is nothing to write anywhere, so the honest answer is
	// `no-cells` (reporting the stored form), not a throw about a path that was
	// never going to be written.
	const exported = doc.cells.filter((c: Cell) => isExportCell(c)).map((c) => c.source);
	if (!exported.length)
		return { written: false, target: info.ok ? info.target : info.path, count: 0, reason: 'no-cells', hazards: [] };
	// Computed once, from the sources this call is about to assemble, and attached
	// to whichever result it returns below.
	const hazards = exportHazards(exported);
	// A configured-but-unresolvable target (base `git` with no repository, a path
	// resolving outside the workspace, an unknown base) is a real error the manual
	// button surfaces and the consequential callers record - exactly where the old
	// `resolveInWorkspace` throw landed.
	if (!info.ok) throw new Error(info.error);
	const target = info.target;

	// KNOWN LIMITATION: `resolveInWorkspace` resolves LEXICALLY (no `realpath`), so a
	// DANGLING `*.py` symlink inside the workspace is followed by the write below and
	// the module lands outside the root. Bounded - an existing destination is still
	// caught by the not-a-generated-module refusal, so nothing is destroyed - and the
	// property is shared by every file writer in the app, so the fix belongs in that
	// one helper (`$lib/server/fstree`), not here.
	const abs = info.abs; // already passed `resolveInWorkspace`, whatever the base
	const sourceName = basename(doc.path);
	const text = generateModule(exported, sourceName);

	if (existsSync(abs)) {
		const existing = safeRead(abs);
		// Idempotent: skip the write when the file already holds identical bytes.
		if (existing === text) {
			return { written: false, target, count: exported.length, reason: 'unchanged', hazards };
		}
		if (existing === null)
			throw new Error(
				`refusing to overwrite ${target}: it exists but could not be read, so it cannot be verified as a Cellar-generated module`
			);
		// The clobber guard, UNCHANGED in what it refuses: Cellar never overwrites a
		// file it did not generate. Only the REPORTING changed - this is a
		// not-written OUTCOME rather than a throw, because it is the ordinary state
		// of an established nbdev repo (the module carries nbdev's own header, and
		// reading `#| export` means every notebook there HAS marks, so every export
		// reaches this branch): as an error it answered the button with a failure and
		// left `lastExportError` set on the two best-effort callers - a channel no
		// human surface reads - for a notebook nothing was wrong with.
		if (isForeignModuleText(existing))
			return { written: false, target, count: exported.length, reason: 'foreign-module', hazards: [] };
	}
	mkdirSync(dirname(abs), { recursive: true });
	writeFileSync(abs, text);
	return { written: true, target, count: exported.length, hazards };
}

/**
 * Is a module WE GENERATED already on disk at this workspace-relative target?
 *
 * The one fact a caller needs before it may say a previously generated module was
 * LEFT in place: `exportNotebookToPy` returns `no-cells` without writing when
 * nothing is marked, and that says nothing about whether a file is there — a
 * target set but never used, or repointed to a fresh path, has generated none. A
 * target that escapes the workspace can hold no module of ours, so the throw
 * `resolveInWorkspace` raises reads as false rather than propagating.
 *
 * PROVENANCE, not mere existence, and through the SAME `isGeneratedModule` test the
 * write site refuses on — the two halves must agree about what "the module" is.
 * The setter only requires a `.py` path inside the workspace, so a target may name
 * a HAND-WRITTEN module; a bare `existsSync` then reported the user's own source
 * file as the leftover module and invited deleting it, which is the sibling clobber
 * guard's whole purpose with the sign flipped. A file we cannot read is not
 * verified as ours, so it reads false too.
 */
export function generatedModuleExists(target: string): boolean {
	try {
		const existing = safeRead(resolveInWorkspace(target));
		return existing !== null && isGeneratedModule(existing);
	} catch {
		return false;
	}
}

/**
 * Does a file Cellar did NOT generate occupy this workspace-relative target?
 *
 * The reporting half of the clobber guard, so the write site's refusal and every
 * caller that has to EXPLAIN it read one rule rather than two that can drift. An
 * EMPTY file is not foreign - the write site overwrites it (pre-creating the module
 * with `touch` is an ordinary workflow), so saying otherwise would explain a refusal
 * that never happened. A file we cannot READ is not foreign either: it was not
 * verified as anything, and that case is still an error at the write site.
 */
export function foreignModuleAt(target: string): boolean {
	try {
		const existing = safeRead(resolveInWorkspace(target));
		return existing !== null && isForeignModuleText(existing);
	} catch {
		return false;
	}
}

/** Is this file text something OTHER than a module Cellar generated? */
function isForeignModuleText(text: string): boolean {
	return text.trim() !== '' && !isGeneratedModule(text);
}

/**
 * Was this file text generated by Cellar? Every generated module opens with
 * `HEADER` on its first line (`generateModule`), so a first-line test is exact in
 * the direction that matters: it can never reject a module Cellar wrote.
 */
function isGeneratedModule(text: string): boolean {
	return text.split('\n', 1)[0].replace(/\r$/, '') === HEADER;
}

function safeRead(abs: string): string | null {
	try {
		return readFileSync(abs, 'utf8');
	} catch {
		return null;
	}
}
