/**
 * Cellar — nbdev-style selective export to a `.py` module.
 *
 * A notebook can name a target `.py` module (`notebook.metadata.cellar.export_target`,
 * nbdev's `#|default_exp`) and mark individual code cells for export
 * (`metadata.cellar.export`, nbdev's `#|export`). The target's path may be
 * expressed relative to the workspace (the default - and what an ABSENT
 * `metadata.cellar.export_base` permanently means, so every pre-base notebook
 * resolves unchanged), to the notebook's own folder, or to the notebook's git
 * root (see `$lib/exportTarget` and `resolveExportTarget` below). This module
 * reads the marked cells IN ORDER and writes a clean Python module: a "do not
 * edit" header, a best-effort `__all__`, and the exported sources concatenated.
 *
 * This is deliberately DISTINCT from the jupytext `.py` export in
 * `jupytext-actions.ts`: that mirrors the WHOLE notebook as a text notebook (cell
 * markers, every cell). This writes a lean module of only the marked cells — the
 * nbdev "library from notebook" model, where the generated module is committed to
 * git (so it is NOT gitignored).
 *
 * Output is deterministic and idempotent: identical marked content yields a
 * byte-identical file, so re-exporting produces no git diff.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, basename, relative, resolve, sep } from 'node:path';
import { resolveInWorkspace, workspaceRoot } from './fstree';
import { gitRootOf } from './git';
import { logicalLines } from './imports';
import { isExportCell } from '../exportRole';
import { isExportBase, type ExportBase } from '../exportTarget';
import type { Cell, NotebookDoc } from './types';

/** The header stamped at the top of every generated module. */
const HEADER = '# AUTOGENERATED BY CELLAR! DO NOT EDIT!';

export interface ExportResult {
	/** true if the file was (re)written; false if unchanged / nothing to do. */
	written: boolean;
	/**
	 * The RESOLVED workspace-relative target path (whatever base it was expressed
	 * under), or null when no target is configured. On the `no-cells` early return
	 * of a target that cannot resolve, the stored form - the only spelling in hand.
	 */
	target: string | null;
	/** number of cells exported. */
	count: number;
	/** why nothing was written, when `written` is false. */
	reason?: 'no-target' | 'no-cells' | 'unchanged';
}

/**
 * Best-effort top-level names for `__all__`, from a single cell's source:
 * top-level `def`/`class` and simple top-level assignments (`X = …`,
 * `X: T = …`, `A, B = …`). Names starting with `_` are omitted (nbdev/Python
 * convention: private). Order is preserved; the caller dedupes across cells.
 *
 * Uses the imports tokenizer's `logicalLines` so `=`/`def`/`class` inside a
 * string or a nested (indented) scope are never mistaken for a definition.
 * Known limits (documented, acceptable for a best-effort `__all__`): augmented
 * assignments (`X += …`), `del`, and dynamically-created names are invisible.
 */
export function topLevelNames(source: string): string[] {
	const names: string[] = [];
	for (const line of logicalLines(source)) {
		if (line.indent !== 0) continue; // only module-level statements define exports
		const head = line.raw.replace(/^\s+/, '');
		// def / class (including `async def`)
		const dc = head.match(/^(?:async\s+)?(?:def|class)\s+([A-Za-z_]\w*)/);
		if (dc) {
			names.push(dc[1]);
			continue;
		}
		// annotated single assignment: `NAME: T = …`
		const ann = head.match(/^([A-Za-z_]\w*)\s*:\s*[^=]+=(?!=)/);
		if (ann) {
			names.push(ann[1]);
			continue;
		}
		// plain assignment (single or tuple): LHS before the first real `=`.
		const eq = head.match(/^([^=]+?)=(?!=)/);
		if (eq) {
			const lhs = eq[1].trim();
			// Only accept an LHS that is purely comma-separated identifiers, so
			// `a == b`, `a[i] = …`, `a.b = …`, `x <= y` never leak in.
			if (/^[A-Za-z_]\w*(\s*,\s*[A-Za-z_]\w*)*$/.test(lhs)) {
				for (const n of lhs.split(',')) names.push(n.trim());
			}
		}
	}
	// Drop private names, dedupe, preserve first-seen order.
	const seen = new Set<string>();
	const out: string[] = [];
	for (const n of names) {
		if (n.startsWith('_') || seen.has(n)) continue;
		seen.add(n);
		out.push(n);
	}
	return out;
}

/** Render a Python list literal for `__all__` (deterministic, single-quoted). */
function renderAll(names: string[]): string {
	if (!names.length) return '__all__ = []';
	return `__all__ = [${names.map((n) => `'${n}'`).join(', ')}]`;
}

/**
 * Build the full module text from the exported cells (already filtered + in
 * document order). Deterministic: a trailing newline, single blank line between
 * blocks, no incidental whitespace, so re-exporting identical content is a
 * byte-for-byte no-op.
 */
export function generateModule(exportedSources: string[], sourceName: string): string {
	const allNames: string[] = [];
	const seen = new Set<string>();
	for (const src of exportedSources) {
		for (const n of topLevelNames(src)) {
			if (!seen.has(n)) {
				seen.add(n);
				allNames.push(n);
			}
		}
	}
	const blocks: string[] = [`${HEADER}\n# Source notebook: ${sourceName}`, renderAll(allNames)];
	for (const src of exportedSources) {
		const trimmed = src.replace(/\s+$/, ''); // drop trailing blank lines within a cell
		if (trimmed) blocks.push(trimmed);
	}
	return blocks.join('\n\n') + '\n';
}

/**
 * A configured export target, resolved through its BASE (`$lib/exportTarget`).
 *
 * `ok:true` carries the stored form (`base` + `path`), the workspace-relative
 * `target` every consumer of "where do the marks land" reads, and the absolute
 * `abs` the exporter writes to. `ok:false` means a target IS configured but
 * cannot resolve - a different fact from "no target", and one that must never
 * be collapsed into it: `moduleWarning` and the UI both key off a null target
 * as "nothing configured", so an unresolvable one has to keep its own shape.
 */
export type ResolvedExportTarget =
	| { ok: true; base: ExportBase; path: string; source: 'metadata' | 'default_exp'; target: string; abs: string }
	| { ok: false; base: string; path: string; source: 'metadata' | 'default_exp'; error: string };

/**
 * The STORED export target for a doc: the notebook-level `export_target` (with
 * its recorded `export_base`; absent = workspace, the permanent legacy meaning),
 * or a `#|default_exp <module>` directive found in any cell (nbdev familiarity;
 * the UI field is the primary mechanism). Returns null when neither is present.
 *
 * A directive target is ALWAYS workspace-relative - nbdev's own dotted-module
 * spelling - and never reads `export_base`, which is a property of the
 * notebook-level SETTING alone: a directive lives in a cell, so pairing it with
 * notebook-level base metadata would make one cell's text mean different files
 * depending on a setting no setter can see from the cell.
 *
 * The directive scan is guarded by a `includes('default_exp')` substring test
 * (`dataframeHtml.ts`'s `/dataframe/i` pre-check, same reason): this is the ONE
 * resolution rule the exporter AND the agent map read, and the map short-circuits
 * only when a notebook-level target IS set — so the COMMON case, a notebook with
 * no export configured at all, would otherwise run a multiline regex over every
 * code cell's full source on the most frequently called agent read tool.
 */
function storedExportTarget(
	doc: NotebookDoc
): { path: string; base: string; source: 'metadata' | 'default_exp' } | null {
	const explicit = doc.metadata?.cellar?.export_target;
	if (typeof explicit === 'string' && explicit.trim()) {
		const rawBase = doc.metadata?.cellar?.export_base;
		const base = typeof rawBase === 'string' && rawBase.trim() ? rawBase.trim() : 'workspace';
		return { path: explicit.trim(), base, source: 'metadata' };
	}
	for (const c of doc.cells) {
		if (c.cell_type !== 'code' || !c.source.includes('default_exp')) continue;
		const m = c.source.match(/^\s*#\s*\|\s*default_exp\s+([^\s#]+)/m);
		if (m) {
			// nbdev writes a dotted module path (`pkg.utils`); map it to a file path.
			const mod = m[1].trim();
			return { path: mod.endsWith('.py') ? mod : mod.replace(/\./g, '/') + '.py', base: 'workspace', source: 'default_exp' };
		}
	}
	return null;
}

/**
 * Resolve a doc's export target through its base, or null when none is
 * configured.
 *
 * The `workspace` branch is byte-for-byte the legacy behavior: the stored form
 * IS the workspace-relative target (no path math, no filesystem), so every
 * notebook written before bases existed keeps resolving to the identical file.
 * The `notebook` and `git` branches resolve the stored form against their base
 * directory and then re-express it workspace-relative - and BOTH still pass the
 * SAME `resolveInWorkspace` guard, so a base is a way to EXPRESS a path, never
 * an escape hatch: a resolution landing outside the workspace is refused here
 * exactly as the setter refuses it at store time.
 *
 * The git root is the repository enclosing the NOTEBOOK (`gitRootOf`, an upward
 * `.git` walk from the notebook's own directory - deliberately not the code
 * root, which may be an external worktree and governs the kernel, not the
 * notebook file). That root may sit ABOVE the workspace (`cd repo/analysis &&
 * cellar`), which is fine: only the RESOLVED module must land inside the
 * workspace. A notebook with no enclosing repository is a first-class
 * `ok:false`, and so is an unknown `export_base` value (a hand-edit): failing
 * closed beats silently reading it as workspace-relative and writing a module
 * to a path nobody chose.
 */
export function resolveExportTarget(doc: NotebookDoc): ResolvedExportTarget | null {
	const stored = storedExportTarget(doc);
	if (!stored) return null;
	const { path, base, source } = stored;
	if (!isExportBase(base)) {
		return {
			ok: false,
			base,
			path,
			source,
			error: `unknown export base ${JSON.stringify(base)}: expected "notebook" or "git" (or no base at all, which means workspace-relative)`
		};
	}
	if (base === 'workspace') {
		try {
			return { ok: true, base, path, source, target: path, abs: resolveInWorkspace(path) };
		} catch (err) {
			// e.g. a hand-edited legacy target escaping the workspace: still "configured
			// but unresolvable", never a throw - the map reads this on every call.
			return { ok: false, base, path, source, error: String((err as Error)?.message ?? err) };
		}
	}
	let baseDir: string;
	if (base === 'notebook') {
		baseDir = dirname(doc.path);
	} else {
		const root = gitRootOf(dirname(doc.path));
		if (!root) {
			return {
				ok: false,
				base,
				path,
				source,
				error: 'the export base is the git root, but this notebook is not inside a git repository - pick another base, or initialize a repository'
			};
		}
		baseDir = root;
	}
	let abs: string;
	try {
		abs = resolveInWorkspace(resolve(baseDir, path));
	} catch {
		return {
			ok: false,
			base,
			path,
			source,
			error: `export target ${path} (relative to the ${base === 'git' ? "notebook's git root" : "notebook's folder"}) resolves outside the workspace - the module can only be written inside the workspace`
		};
	}
	return { ok: true, base, path, source, target: relative(resolve(workspaceRoot()), abs).split(sep).join('/'), abs };
}

/**
 * The workspace-relative path a configured target RESOLVES to, or null when no
 * target is configured OR it cannot resolve. Callers that must tell those two
 * nulls apart (the exporter, the agent fields) use `resolveExportTarget`.
 */
export function resolveTarget(doc: NotebookDoc): string | null {
	const r = resolveExportTarget(doc);
	return r && r.ok ? r.target : null;
}

/**
 * Generate the `.py` module for a notebook document. Writes only when a target is
 * configured AND at least one code cell is marked for export AND the generated
 * text differs from what is already on disk (so an unchanged re-export touches
 * nothing — no mtime churn, no git diff). The write is path-guarded to the
 * workspace and creates parent directories as needed.
 *
 * Never throws for the "nothing to do" cases (no target / no marked cells): the
 * caller (auto-on-save) must not have a save broken by an absent target. A bad
 * target path (escapes the workspace) still throws — that is a real error the
 * manual button surfaces to the user.
 *
 * It also REFUSES to overwrite a file it did not generate. The write is a
 * whole-file replacement, so a target naming an ordinary source file would destroy
 * it — and while `setExportTarget` refuses a non-`.py` path, a `#|default_exp`
 * directive resolves straight to a path here without passing that setter, and a
 * `.py` path may perfectly well be a hand-written module. Every generated module
 * opens with `HEADER`, so testing the file already on disk for it rejects nothing
 * Cellar wrote. The refusal throws, which auto-on-save records as `lastExportError`
 * (never breaking the notebook save) and the manual button surfaces directly.
 *
 * An EMPTY file (zero bytes, or whitespace only) is overwritten, not refused: the
 * guard exists to protect CONTENT, and there is none. Pre-creating the module
 * (`touch utils.py`, or the explorer's "New file") before naming the target is an
 * ordinary workflow, and refusing it stopped the module regenerating on every
 * later save through a path no UI surface reads.
 */
export function exportNotebookToPy(doc: NotebookDoc): ExportResult {
	const info = resolveExportTarget(doc);
	if (!info) return { written: false, target: null, count: 0, reason: 'no-target' };

	// The nothing-to-do contract holds even over an unresolvable target: with no
	// cell marked there is nothing to write anywhere, so the honest answer is
	// `no-cells` (reporting the stored form), not a throw about a path that was
	// never going to be written.
	const exported = doc.cells.filter((c: Cell) => isExportCell(c)).map((c) => c.source);
	if (!exported.length)
		return { written: false, target: info.ok ? info.target : info.path, count: 0, reason: 'no-cells' };
	// A configured-but-unresolvable target (base `git` with no repository, a path
	// resolving outside the workspace, an unknown base) is a real error the manual
	// button surfaces and auto-on-save records - exactly where the old
	// `resolveInWorkspace` throw landed.
	if (!info.ok) throw new Error(info.error);
	const target = info.target;

	// KNOWN LIMITATION: `resolveInWorkspace` resolves LEXICALLY (no `realpath`), so a
	// DANGLING `*.py` symlink inside the workspace is followed by the write below and
	// the module lands outside the root. Bounded - an existing destination is still
	// caught by the not-a-generated-module refusal, so nothing is destroyed - and the
	// property is shared by every file writer in the app, so the fix belongs in that
	// one helper (`$lib/server/fstree`), not here.
	const abs = info.abs; // already passed `resolveInWorkspace`, whatever the base
	const sourceName = basename(doc.path);
	const text = generateModule(exported, sourceName);

	if (existsSync(abs)) {
		const existing = safeRead(abs);
		// Idempotent: skip the write when the file already holds identical bytes.
		if (existing === text) {
			return { written: false, target, count: exported.length, reason: 'unchanged' };
		}
		if (existing === null)
			throw new Error(
				`refusing to overwrite ${target}: it exists but could not be read, so it cannot be verified as a Cellar-generated module`
			);
		if (!isGeneratedModule(existing) && existing.trim() !== '')
			throw new Error(
				`refusing to overwrite ${target}: it is not a Cellar-generated module (it does not begin with "${HEADER}") - point the export target at a path Cellar owns, or delete that file`
			);
	}
	mkdirSync(dirname(abs), { recursive: true });
	writeFileSync(abs, text);
	return { written: true, target, count: exported.length };
}

/**
 * Is a module WE GENERATED already on disk at this workspace-relative target?
 *
 * The one fact a caller needs before it may say a previously generated module was
 * LEFT in place: `exportNotebookToPy` returns `no-cells` without writing when
 * nothing is marked, and that says nothing about whether a file is there — a
 * target set but never used, or repointed to a fresh path, has generated none. A
 * target that escapes the workspace can hold no module of ours, so the throw
 * `resolveInWorkspace` raises reads as false rather than propagating.
 *
 * PROVENANCE, not mere existence, and through the SAME `isGeneratedModule` test the
 * write site refuses on — the two halves must agree about what "the module" is.
 * The setter only requires a `.py` path inside the workspace, so a target may name
 * a HAND-WRITTEN module; a bare `existsSync` then reported the user's own source
 * file as the leftover module and invited deleting it, which is the sibling clobber
 * guard's whole purpose with the sign flipped. A file we cannot read is not
 * verified as ours, so it reads false too.
 */
export function generatedModuleExists(target: string): boolean {
	try {
		const existing = safeRead(resolveInWorkspace(target));
		return existing !== null && isGeneratedModule(existing);
	} catch {
		return false;
	}
}

/**
 * Was this file text generated by Cellar? Every generated module opens with
 * `HEADER` on its first line (`generateModule`), so a first-line test is exact in
 * the direction that matters: it can never reject a module Cellar wrote.
 */
function isGeneratedModule(text: string): boolean {
	return text.split('\n', 1)[0].replace(/\r$/, '') === HEADER;
}

function safeRead(abs: string): string | null {
	try {
		return readFileSync(abs, 'utf8');
	} catch {
		return null;
	}
}
