// @vitest-environment jsdom
/**
 * `$lib/dataframeHtml` reads a tabular `text/html` repr into the grid's payload,
 * and this file is the proof that it reads the LAYOUT rather than assuming pandas'.
 *
 * The defect it exists to prevent is not a crash: the parser hardcoded pandas'
 * leading index cell (`firstThs.slice(1)`), so a producer without one - polars, and
 * `df.to_html(index=False)` - lost its FIRST REAL COLUMN, whose values were promoted
 * to the row index while every dtype shifted one place along. Nothing failed; the
 * grid looked entirely normal and showed the wrong data. So the assertions here name
 * COLUMNS AND VALUES, never merely "it parsed".
 *
 * Every input is a VERBATIM repr captured from a real pandas 2.3.3 / polars 1.44.1
 * (`tests/unit/fixtures/dataframe-html-reprs.json`, regenerated by its sibling
 * `.gen.py`), because the whole question is what those libraries actually emit -
 * a hand-typed approximation is the parser's own assumptions written twice.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseDataFrameHtml } from '../../src/lib/dataframeHtml';

const REPO = process.cwd();
const F = JSON.parse(
	readFileSync(join(REPO, 'tests/unit/fixtures/dataframe-html-reprs.json'), 'utf8')
) as Record<string, string> & { polars_captain_columns: string[] };

describe('polars: every column, its real dtypes, and no stray quotes', () => {
	it("keeps the captain's 17-column frame whole - `uuid` was the column that vanished", () => {
		const p = parseDataFrameHtml(F.polars_captain_17col);
		expect(p).not.toBeNull();
		expect(p!.columns).toEqual(F.polars_captain_columns);
		expect(p!.columns.length).toBe(17);
		// The FIRST column is the one the old `slice(1)` deleted, and its values are
		// what it promoted to the row index. Both halves, or a fix that merely
		// renamed the columns would pass.
		expect(p!.columns[0]).toBe('uuid');
		expect(p!.data.map((r) => r[0])).toEqual(['a1b2c3', 'd4e5f6', '071819']);
		expect(p!.data.every((r) => r.length === 17)).toBe(true);
		expect(p!.total_cols).toBe(17);
	});

	it('reports no index at all rather than borrowing a column for one', () => {
		const p = parseDataFrameHtml(F.polars_captain_17col)!;
		expect(p.has_index).toBe(false);
		expect(p.index).toEqual(['', '', '']);
	});

	it('takes the dtypes polars DECLARES, so a numeric-looking string stays a string', () => {
		const p = parseDataFrameHtml(F.polars_captain_17col)!;
		const dtypeOf = (c: string) => p.dtypes[p.columns.indexOf(c)];
		expect(dtypeOf('uuid')).toBe('str');
		expect(dtypeOf('bidder_id')).toBe('str');
		expect(dtypeOf('bid_round')).toBe('i64');
		expect(dtypeOf('floor')).toBe('f64');
		expect(dtypeOf('win')).toBe('bool');
		// `bidder_id` is a str column whose values look like integers. Inferring from
		// the rendered text would retype the whole column; the declared dtype is what
		// keeps `"5006"` the string 5006.
		const bid = p.columns.indexOf('bidder_id');
		expect(p.data.map((r) => r[bid])).toEqual(['5006', '5006', '3788']);
		expect(p.data.every((r) => typeof r[bid] === 'string')).toBe(true);
		// ...while a genuinely numeric column really is numeric.
		const round = p.columns.indexOf('bid_round');
		expect(p.data.map((r) => r[round])).toEqual([1, 2, 1]);
	});

	it('strips polars’ own quotes, including around an embedded quote and an empty string', () => {
		const p = parseDataFrameHtml(F.polars_quotes_nulls)!;
		expect(p.columns).toEqual(['id', 'n', 'say']);
		// polars does not escape an inner quote (`say "hi"` renders `"say "hi""`),
		// so one matched pair is exactly what comes off.
		expect(p.data.map((r) => r[2])).toEqual(['say "hi"', '', null]);
		// A bare `null` is missing; a quoted one would be the string.
		expect(p.data.map((r) => r[0])).toEqual(['5006', null, '007']);
		expect(p.data.map((r) => r[1])).toEqual([1, null, 3]);
	});

	it('renders a small frame with both real columns', () => {
		const p = parseDataFrameHtml(F.polars_small)!;
		expect(p.columns).toEqual(['a', 'b']);
		expect(p.data).toEqual([
			[1, 'x'],
			[2, 'y']
		]);
		expect(p.total_rows).toBe(2);
	});

	it('carries polars’ richer dtypes through verbatim', () => {
		const p = parseDataFrameHtml(F.polars_dtypes)!;
		expect(p.columns).toEqual(['d', 'f', 'b', 'l']);
		expect(p.dtypes).toEqual(['date', 'f64', 'bool', 'list[i64]']);
	});

	it('drops the row-truncation row and reports the DECLARED total', () => {
		const p = parseDataFrameHtml(F.polars_row_truncation)!;
		expect(p.total_rows).toBe(40);
		expect(p.truncated_rows).toBe(true);
		expect(p.data.length).toBeLessThan(40);
		// No `…` leaked into the rows.
		expect(p.data.flat().some((v) => v === '…' || v === '...')).toBe(false);
	});

	it('drops the column-truncation column and still reports 100 columns', () => {
		const p = parseDataFrameHtml(F.polars_col_truncation)!;
		expect(p.total_cols).toBe(100);
		expect(p.truncated_cols).toBe(true);
		expect(p.columns).not.toContain('…');
		expect(p.columns[0]).toBe('c0');
		expect(p.columns.at(-1)).toBe('c99');
		expect(p.data.every((r) => r.length === p.columns.length)).toBe(true);
	});

	it('reads a Series’ one-element `shape: (n,)` as one column', () => {
		const p = parseDataFrameHtml(F.polars_series)!;
		expect(p.columns).toEqual(['s']);
		expect(p.data).toEqual([[1], [2], [3]]);
		expect(p.total_cols).toBe(1);
	});
});

describe('the refusal: a parsed shape that disagrees with the declared one', () => {
	/** polars' repr, minus one header cell - the shape the old parser rendered. */
	const dropOneHeader = F.polars_small.replace('<th>b</th>', '');

	it('refuses a frame whose columns do not add up, rather than showing a wrong grid', () => {
		expect(parseDataFrameHtml(dropOneHeader)).toBeNull();
	});

	it('refuses when the declared count is HIGHER with no truncation marker', () => {
		const lying = F.polars_small.replace('shape: (2, 2)', 'shape: (2, 9)');
		expect(parseDataFrameHtml(lying)).toBeNull();
	});

	it('refuses when a truncation marker is present but the count already adds up', () => {
		// An ellipsis column over a complete count means the layout is not what we
		// read it to be - the mirror of the missing-column case.
		const p = parseDataFrameHtml(F.polars_col_truncation)!;
		const faked = F.polars_col_truncation.replace('shape: (2, 100)', `shape: (2, ${p.columns.length})`);
		expect(parseDataFrameHtml(faked)).toBeNull();
	});

	it('refuses a body row whose cell count disagrees with the header', () => {
		const short = F.pandas_plain.replace('<td>x</td>', '');
		expect(parseDataFrameHtml(short)).toBeNull();
	});

	it('refuses more rendered rows than the frame declares', () => {
		const lying = F.polars_small.replace('shape: (2, 2)', 'shape: (1, 2)');
		expect(parseDataFrameHtml(lying)).toBeNull();
	});
});

describe('pandas is untouched', () => {
	it('parses the plain repr exactly as before, index and all', () => {
		const p = parseDataFrameHtml(F.pandas_plain)!;
		expect(p.columns).toEqual(['a', 'b']);
		expect(p.index).toEqual([0, 1]);
		expect(p.has_index).toBe(true);
		expect(p.data).toEqual([
			[1, 'x'],
			[2, 'y']
		]);
	});

	it('keeps a named index as the index name, not as a column', () => {
		const p = parseDataFrameHtml(F.pandas_named_index)!;
		expect(p.columns).toEqual(['b']);
		expect(p.index_name).toBe('a');
		expect(p.index).toEqual([1, 2]);
	});

	it("reads `df.columns.name` as the index placeholder, not as a missing index", () => {
		// The case that rules out deciding from the header: the leading `<th>` is
		// NON-empty here and is still the index cell.
		const p = parseDataFrameHtml(F.pandas_columns_name)!;
		expect(p.columns).toEqual(['a', 'b']);
		expect(p.has_index).toBe(true);
		expect(p.data).toEqual([[1, 2]]);
	});

	it('parses a MultiIndex row label by joining its parts', () => {
		const p = parseDataFrameHtml(F.pandas_multiindex_rows)!;
		expect(p.columns).toEqual(['v']);
		// The continuation row's outer level is spanned by a `rowspan` above it, so it
		// carries only the inner label - which `coerceCell` reads as the number it is.
		expect(p.index).toEqual(['a / 1', 2]);
	});

	it('keeps the truncation footer as the total', () => {
		const p = parseDataFrameHtml(F.pandas_row_truncation)!;
		expect(p.total_rows).toBe(200);
		expect(p.truncated_rows).toBe(true);
		expect(p.columns).toEqual(['v']);
	});

	it('drops pandas’ ellipsis column and reports the real width', () => {
		const p = parseDataFrameHtml(F.pandas_col_truncation)!;
		expect(p.columns).not.toContain('...');
		expect(p.total_cols).toBe(30);
		expect(p.data.every((r) => r.length === p.columns.length)).toBe(true);
	});

	it('now reads `to_html(index=False)` too - the same missing-column bug', () => {
		const p = parseDataFrameHtml(F.pandas_to_html_no_index)!;
		expect(p.columns).toEqual(['a', 'b']);
		expect(p.has_index).toBe(false);
		expect(p.data).toEqual([
			[1, 'x'],
			[2, 'y']
		]);
	});

	it('still refuses MultiIndex columns and non-dataframe html', () => {
		expect(parseDataFrameHtml(F.pandas_multiindex_cols)).toBeNull();
		expect(parseDataFrameHtml('<div><table><tr><td>hi</td></tr></table></div>')).toBeNull();
		expect(parseDataFrameHtml('')).toBeNull();
		expect(parseDataFrameHtml(null)).toBeNull();
	});
});

describe('pandas Styler: the FORMATTED values, the caption, and the layout it declares', () => {
	it("renders as a grid at all - it used to miss both gates and stay a static table", () => {
		expect(parseDataFrameHtml(F.styler_bare)).not.toBeNull();
	});

	it('keeps the formatted values, which is the whole reason `.style` was written', () => {
		const p = parseDataFrameHtml(F.styler_plain)!;
		expect(p.columns).toEqual(['rev', 'share']);
		// `{:,.2f}` and `{:.1%}` as the user asked for them - `styler.data`, the only
		// public handle a kernel-side formatter would have, holds 1234.5 and 0.1234.
		expect(p.data).toEqual([
			['1,234.50', '12.3%'],
			['98,765.25', '87.7%']
		]);
		expect(p.index).toEqual(['a', 'b']);
	});

	it('carries `set_caption` through to the payload', () => {
		expect(parseDataFrameHtml(F.styler_plain)!.caption).toBe('Revenue by arm');
		// A plain frame has none, and the field stays absent rather than empty.
		expect(parseDataFrameHtml(F.pandas_plain)!.caption).toBeUndefined();
	});

	it("honours `.hide(axis='index')` - the captain's own call shape", () => {
		const p = parseDataFrameHtml(F.styler_hide_index)!;
		expect(p.columns).toEqual(['rev', 'share']);
		expect(p.has_index).toBe(false);
		expect(p.caption).toBe('Floors');
		expect(p.data[0]).toEqual(['1,234.50', '12.3%']);
	});

	it('reads a Styler index NAME from its own `index_name` row', () => {
		const p = parseDataFrameHtml(F.styler_named_index)!;
		expect(p.columns).toEqual(['v']);
		expect(p.index_name).toBe('k');
		expect(p.index).toEqual(['a', 'b']);
	});

	it('renders a gradient Styler as a grid too - the colours are what is dropped', () => {
		const p = parseDataFrameHtml(F.styler_gradient)!;
		expect(p.columns).toEqual(['rev', 'share']);
		expect(p.data).toEqual([
			[1234.5, 0.1234],
			[98765.25, 0.8766]
		]);
	});

	it('is admitted by its own cheap token, and only under the size ceiling', () => {
		// Nothing that never says `col_heading` reaches the DOM parser at all.
		expect(parseDataFrameHtml('<table id="T_x"><tbody><tr><td>1</td></tr></tbody></table>')).toBeNull();
		// Past 2 MiB it keeps the sandboxed iframe rather than being walked cell by cell.
		const padded = F.styler_plain + `<!--${'x'.repeat(2 * 1024 * 1024)}-->`;
		expect(parseDataFrameHtml(padded)).toBeNull();
		// The `class="dataframe"` path is bounded by pandas' display options, so the
		// ceiling deliberately does not apply to it.
		const bigPandas = F.pandas_plain + `<!--${'x'.repeat(2 * 1024 * 1024)}-->`;
		expect(parseDataFrameHtml(bigPandas)).not.toBeNull();
	});

	it('still refuses a MultiIndex-column Styler', () => {
		expect(parseDataFrameHtml(F.styler_multiindex_cols)).toBeNull();
	});
});

describe('DataFrameGrid source guard: the index column follows has_index', () => {
	// vitest deliberately runs without the SvelteKit plugin (see vitest.config.ts),
	// so the component cannot be mounted here; the behavioural proof is in
	// `tests/e2e/dataframe-polars-styler.spec.ts`. What these guard is the one
	// expression the whole rule is: absent MUST read as true, or every pandas
	// payload the kernel emits (which carries no such field) loses its index.
	const src = readFileSync(join(REPO, 'src/lib/DataFrameGrid.svelte'), 'utf8');

	it('derives hasIndex as "absent means true"', () => {
		expect(src).toMatch(/const hasIndex = \$derived\(payload\?\.has_index !== false\)/);
		// The regression: anything that reads an absent field as false.
		expect(src).not.toMatch(/has_index === true/);
	});

	it('gates both the index header and the index cell on it', () => {
		expect(src).toMatch(/\{#if hasIndex\}<th/);
		expect(src).toMatch(/\{#if hasIndex\}<td[^>]*data-testid="df-index-cell"/);
		// The empty-state colspan has to follow, or a no-index grid's message is
		// one column too wide.
		expect(src).toContain('colspan={columns.length + (hasIndex ? 1 : 0)}');
	});
});
