import { describe, it, expect, vi } from 'vitest';
import { topLevelNames, generateModule, resolveExportTarget } from '../../src/lib/server/export-py';
import type { NotebookDoc } from '../../src/lib/server/types';

// The REAL scanner, counted at the module boundary `export-py.ts` calls it through -
// which is what makes "resolves cheaply" an observation rather than an assertion
// about an implementation detail. Behaviour is untouched: every call delegates.
const scanner = vi.hoisted(() => ({ calls: 0 }));
vi.mock('../../src/lib/nbdevDirectives', async (importOriginal) => {
	const real = await importOriginal<typeof import('../../src/lib/nbdevDirectives')>();
	return {
		...real,
		nbdevDirective: (source: string | null | undefined, name: string) => {
			scanner.calls++;
			return real.nbdevDirective(source, name);
		}
	};
});

describe('topLevelNames', () => {
	it('collects top-level def / class / assignments, skips private + nested', () => {
		const src = [
			'import os',
			'X = 1',
			'y: int = 2',
			'A, B = 3, 4',
			'_hidden = 5',
			'def foo():',
			'    inner = 6',
			'    return inner',
			'class Bar:',
			'    def method(self): pass',
			'async def baz(): pass'
		].join('\n');
		expect(topLevelNames(src)).toEqual(['X', 'y', 'A', 'B', 'foo', 'Bar', 'baz']);
	});

	it('ignores comparisons, subscript/attr assignment, and strings', () => {
		const src = ['a == b', 'd["k"] = 1', 'obj.attr = 2', 's = "def not_a_def(): x = 1"'].join('\n');
		expect(topLevelNames(src)).toEqual(['s']);
	});
});

describe('generateModule', () => {
	const cells = ['def add(a, b):\n    return a + b', 'PI = 3.14'];

	it('emits header, source-notebook line, __all__, and cells in order', () => {
		const out = generateModule(cells, 'analysis.ipynb');
		expect(out).toBe(
			'# AUTOGENERATED BY CELLAR! DO NOT EDIT!\n' +
				'# Source notebook: analysis.ipynb\n\n' +
				"__all__ = ['add', 'PI']\n\n" +
				'def add(a, b):\n    return a + b\n\n' +
				'PI = 3.14\n'
		);
	});

	it('is deterministic / idempotent for identical input', () => {
		expect(generateModule(cells, 'n.ipynb')).toBe(generateModule(cells, 'n.ipynb'));
	});

	it('emits an empty __all__ when nothing is exportable', () => {
		expect(generateModule(['print(1)'], 'n.ipynb')).toContain('__all__ = []');
	});
});

describe('resolveExportTarget', () => {
	const doc = (over: Partial<NotebookDoc>): NotebookDoc => ({ path: '/ws/n.ipynb', cells: [], ...over });

	it('prefers the explicit notebook-level target', () => {
		expect(resolveExportTarget(doc({ metadata: { cellar: { export_target: 'utils.py' } } }))).toMatchObject({
			ok: true,
			base: 'workspace',
			source: 'metadata',
			target: 'utils.py'
		});
	});

	it('honors a #|default_exp directive and maps dotted modules to a path', () => {
		const d = doc({ cells: [{ id: '1', cell_type: 'code', source: '#|default_exp pkg.utils\nX = 1' }] });
		expect(resolveExportTarget(d)).toMatchObject({ ok: true, source: 'default_exp', target: 'pkg/utils.py' });
	});

	it('returns null when neither is present', () => {
		expect(resolveExportTarget(doc({}))).toBeNull();
	});

	it('refuses cheaply, never reaching the scanner for a notebook that mentions no directive', () => {
		// This is the ONE resolution rule the exporter and `get_notebook_map` share,
		// and the map short-circuits only when a notebook-level target IS set - so the
		// COMMON case (no export configured at all) resolves on every call of the most
		// frequently used agent read tool. It must cost a substring test per cell, not
		// a scan of every code cell's source.
		//
		// Observed at the scanner's own module boundary, so deleting the
		// `includes('default_exp')` pre-check FAILS this: the walk would then be entered
		// once per cell. (The per-CELL `#| export` read has no such guard and is right
		// not to - see `nbdevDirectives.ts`'s Cost section for the measurement; that
		// predicate answers one cell from its first line, while this one must clear
		// every cell of the document before it can conclude "no target".)
		const source = 'x = 1\ndf = load()\n'.repeat(200);
		const cells = Array.from({ length: 40 }, (_, i) => ({ id: `c${i}`, cell_type: 'code' as const, source }));
		scanner.calls = 0;
		expect(resolveExportTarget(doc({ cells }))).toBeNull();
		expect(scanner.calls).toBe(0);

		// ...and the guard never costs a real directive its match. A REAL directive is
		// one nbdev would read: in the cell's LEADING block. The scan reads nbdev's own
		// rule now (`$lib/nbdevDirectives`), which is also what bounds its cost - the
		// block ends at the first ordinary line, so a 400-line cell costs one line.
		const withDirective = doc({ cells: [{ id: 'a', cell_type: 'code', source: `#|default_exp lib.cheap\n${source}` }] });
		scanner.calls = 0;
		expect(resolveExportTarget(withDirective)).toMatchObject({ ok: true, target: 'lib/cheap.py' });
		// The counter is not vacuous in the other direction either: the scanner IS the
		// thing that answers once a cell mentions the directive.
		expect(scanner.calls).toBe(1);

		// ...and a `#|default_exp` sitting AFTER code is not a directive to nbdev, so
		// it must not be one here either. Honouring it was the "half-speaks nbdev"
		// defect: a target resolved from text nbdev ignores, written to a file nbdev
		// would never write (scout report section 5.2).
		const afterCode = doc({ cells: [{ id: 'a', cell_type: 'code', source: `${source}#|default_exp lib.cheap` }] });
		expect(resolveExportTarget(afterCode)).toBeNull();
	});
});
