import { describe, it, expect } from 'vitest';
import { topLevelNames, generateModule, resolveTarget } from '../../src/lib/server/export-py';
import type { NotebookDoc } from '../../src/lib/server/types';

describe('topLevelNames', () => {
	it('collects top-level def / class / assignments, skips private + nested', () => {
		const src = [
			'import os',
			'X = 1',
			'y: int = 2',
			'A, B = 3, 4',
			'_hidden = 5',
			'def foo():',
			'    inner = 6',
			'    return inner',
			'class Bar:',
			'    def method(self): pass',
			'async def baz(): pass'
		].join('\n');
		expect(topLevelNames(src)).toEqual(['X', 'y', 'A', 'B', 'foo', 'Bar', 'baz']);
	});

	it('ignores comparisons, subscript/attr assignment, and strings', () => {
		const src = ['a == b', 'd["k"] = 1', 'obj.attr = 2', 's = "def not_a_def(): x = 1"'].join('\n');
		expect(topLevelNames(src)).toEqual(['s']);
	});
});

describe('generateModule', () => {
	const cells = ['def add(a, b):\n    return a + b', 'PI = 3.14'];

	it('emits header, source-notebook line, __all__, and cells in order', () => {
		const out = generateModule(cells, 'analysis.ipynb');
		expect(out).toBe(
			'# AUTOGENERATED BY CELLAR! DO NOT EDIT!\n' +
				'# Source notebook: analysis.ipynb\n\n' +
				"__all__ = ['add', 'PI']\n\n" +
				'def add(a, b):\n    return a + b\n\n' +
				'PI = 3.14\n'
		);
	});

	it('is deterministic / idempotent for identical input', () => {
		expect(generateModule(cells, 'n.ipynb')).toBe(generateModule(cells, 'n.ipynb'));
	});

	it('emits an empty __all__ when nothing is exportable', () => {
		expect(generateModule(['print(1)'], 'n.ipynb')).toContain('__all__ = []');
	});
});

describe('resolveTarget', () => {
	const doc = (over: Partial<NotebookDoc>): NotebookDoc => ({ path: '/ws/n.ipynb', cells: [], ...over });

	it('prefers the explicit notebook-level target', () => {
		expect(resolveTarget(doc({ metadata: { cellar: { export_target: 'utils.py' } } }))).toBe('utils.py');
	});

	it('honors a #|default_exp directive and maps dotted modules to a path', () => {
		const d = doc({ cells: [{ id: '1', cell_type: 'code', source: '#|default_exp pkg.utils\nX = 1' }] });
		expect(resolveTarget(d)).toBe('pkg/utils.py');
	});

	it('returns null when neither is present', () => {
		expect(resolveTarget(doc({}))).toBeNull();
	});
});
