import { describe, it, expect, vi } from 'vitest';
import { topLevelNames, generateModule, resolveExportTarget } from '../../src/lib/server/export-py';
import type { NotebookDoc } from '../../src/lib/server/types';

describe('topLevelNames', () => {
	it('collects top-level def / class / assignments, skips private + nested', () => {
		const src = [
			'import os',
			'X = 1',
			'y: int = 2',
			'A, B = 3, 4',
			'_hidden = 5',
			'def foo():',
			'    inner = 6',
			'    return inner',
			'class Bar:',
			'    def method(self): pass',
			'async def baz(): pass'
		].join('\n');
		expect(topLevelNames(src)).toEqual(['X', 'y', 'A', 'B', 'foo', 'Bar', 'baz']);
	});

	it('ignores comparisons, subscript/attr assignment, and strings', () => {
		const src = ['a == b', 'd["k"] = 1', 'obj.attr = 2', 's = "def not_a_def(): x = 1"'].join('\n');
		expect(topLevelNames(src)).toEqual(['s']);
	});
});

describe('generateModule', () => {
	const cells = ['def add(a, b):\n    return a + b', 'PI = 3.14'];

	it('emits header, source-notebook line, __all__, and cells in order', () => {
		const out = generateModule(cells, 'analysis.ipynb');
		expect(out).toBe(
			'# AUTOGENERATED BY CELLAR! DO NOT EDIT!\n' +
				'# Source notebook: analysis.ipynb\n\n' +
				"__all__ = ['add', 'PI']\n\n" +
				'def add(a, b):\n    return a + b\n\n' +
				'PI = 3.14\n'
		);
	});

	it('is deterministic / idempotent for identical input', () => {
		expect(generateModule(cells, 'n.ipynb')).toBe(generateModule(cells, 'n.ipynb'));
	});

	it('emits an empty __all__ when nothing is exportable', () => {
		expect(generateModule(['print(1)'], 'n.ipynb')).toContain('__all__ = []');
	});
});

describe('resolveExportTarget', () => {
	const doc = (over: Partial<NotebookDoc>): NotebookDoc => ({ path: '/ws/n.ipynb', cells: [], ...over });

	it('prefers the explicit notebook-level target', () => {
		expect(resolveExportTarget(doc({ metadata: { cellar: { export_target: 'utils.py' } } }))).toMatchObject({
			ok: true,
			base: 'workspace',
			source: 'metadata',
			target: 'utils.py'
		});
	});

	it('honors a #|default_exp directive and maps dotted modules to a path', () => {
		const d = doc({ cells: [{ id: '1', cell_type: 'code', source: '#|default_exp pkg.utils\nX = 1' }] });
		expect(resolveExportTarget(d)).toMatchObject({ ok: true, source: 'default_exp', target: 'pkg/utils.py' });
	});

	it('returns null when neither is present', () => {
		expect(resolveExportTarget(doc({}))).toBeNull();
	});

	it('refuses cheaply, running no regex over a notebook that mentions no directive', () => {
		// This is the ONE resolution rule the exporter and `get_notebook_map` share,
		// and the map short-circuits only when a notebook-level target IS set - so the
		// COMMON case (no export configured at all) resolves on every call of the most
		// frequently used agent read tool. It must cost a substring test, not a
		// multiline regex over every code cell's full source.
		const source = 'x = 1\ndf = load()\n'.repeat(200);
		const cells = Array.from({ length: 40 }, (_, i) => ({ id: `c${i}`, cell_type: 'code' as const, source }));
		const spy = vi.spyOn(String.prototype, 'match');
		try {
			expect(resolveExportTarget(doc({ cells }))).toBeNull();
			expect(spy).not.toHaveBeenCalled();
		} finally {
			spy.mockRestore();
		}

		// ...and the guard never costs a real directive its match.
		const withDirective = doc({ cells: [{ id: 'a', cell_type: 'code', source: `${source}#|default_exp lib.cheap` }] });
		expect(resolveExportTarget(withDirective)).toMatchObject({ ok: true, target: 'lib/cheap.py' });
	});
});
