/**
 * The generated module a LANGUAGE SWITCH leaves behind, and the rules that keep
 * naming it honest and cheap.
 *
 * `setNotebookLanguage` re-expresses the stored export target (`utils.py` ->
 * `utils.mojo`) and RENAMES NOTHING ON DISK - Cellar never deletes or truncates a
 * generated module the user's repository holds. So the old file stays: in an nbdev
 * repo it is git-TRACKED and still importable, while this notebook has stopped
 * writing it. Left silent, that is someone staring at a module that looks current
 * and is not, so the path is NAMED once for the notebook and the decision is
 * theirs.
 *
 * Three claims, each with its opposite pinned beside it:
 *
 *  - IT IS REALLY THERE. Driven through the REAL document layer and the REAL
 *    exporter, so the leftover is a file a switch actually produced rather than a
 *    fixture describing one.
 *  - PROVENANCE, NOT MERE EXISTENCE. A hand-written module at the sibling path, and
 *    one ANOTHER notebook generated, are both refused - pointing at either and
 *    calling it a stale Cellar module is a false claim, and it is the mistake the
 *    sibling clobber guard exists to prevent with the sign flipped.
 *  - IT COSTS AN ORDINARY NOTEBOOK NOTHING. `getNotebook` runs on the process
 *    carrying the kernel websockets and the SSE fan-out, so the check narrows
 *    BEFORE it touches the filesystem. The syscall IS the subject and both cases
 *    answer `null`, so nothing in the return value can tell the ordering apart -
 *    `node:fs` is wrapped (the `export-hazard-cost.test.ts` precedent) and the
 *    opens are counted. The wrapper delegates, so every read here is a real read.
 */
import { describe, it, expect, beforeAll, vi } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';

const { opens } = vi.hoisted(() => ({ opens: [] as string[] }));

vi.mock('node:fs', async () => {
	const actual = await vi.importActual<typeof import('node:fs')>('node:fs');
	const openSync = (...args: Parameters<typeof actual.openSync>) => {
		opens.push(String(args[0]));
		return actual.openSync(...args);
	};
	return { ...actual, default: { ...actual, openSync }, openSync };
});

vi.mock('../../src/lib/server/dataflow', () => ({
	getNotebookStaleness: async () => ({ sid: null, cells: {} }),
	analyzeDataflow: async () => ({})
}));

const HEADER = '# AUTOGENERATED BY CELLAR! DO NOT EDIT!';

let WS: string;
let nbmod: typeof import('../../src/lib/server/notebook');

beforeAll(async () => {
	WS = mkdtempSync(join(tmpdir(), 'cellar-export-orphan-'));
	process.env.CELLAR_WORKSPACE = WS;
	nbmod = await import('../../src/lib/server/notebook');
});

/** A notebook with one marked code cell, exporting to `target`. */
function exportingNotebook(rel: string, target: string, source = 'def one():\n    return 1\n') {
	const nb = nbmod.resolveNotebookPath(rel);
	nbmod.createNotebook(rel);
	const cell = nbmod.addCell(null, 'code', nb, null, source);
	nbmod.setExportTarget(target, nb);
	nbmod.setCellExports([cell.id], true, nb);
	return nb;
}

/** Write a file into the workspace, creating its directory. */
function put(rel: string, text: string) {
	const abs = join(WS, rel);
	mkdirSync(dirname(abs), { recursive: true });
	writeFileSync(abs, text);
	return abs;
}

/** Every workspace module path this call OPENED (the sibling probe's syscall). */
function moduleOpens(run: () => void): string[] {
	opens.length = 0;
	run();
	return opens.filter((p) => /\.(py|mojo)$/i.test(p));
}

describe('a language switch leaves the old generated module on disk, and it is NAMED', () => {
	it('reports the sibling the target no longer names, after a real switch', () => {
		const nb = exportingNotebook('lib.ipynb', 'mod/util.py');
		// Nothing is left behind yet, so the ordinary notebook says nothing.
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBeNull();
		expect(readFileSync(join(WS, 'mod/util.py'), 'utf8').startsWith(HEADER)).toBe(true);

		nbmod.setNotebookLanguage('mojo', nb);

		// The SETTING moved; the FILE did not - which is the whole reason this exists.
		expect(nbmod.getNotebook(nb).exportTarget).toBe('mod/util.mojo');
		expect(existsSync(join(WS, 'mod/util.mojo'))).toBe(true);
		expect(existsSync(join(WS, 'mod/util.py'))).toBe(true);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBe('mod/util.py');
	});

	it('follows the switch BACK, so the leftover is always the one that is stale now', () => {
		const nb = exportingNotebook('back.ipynb', 'mod/back.py');
		nbmod.setNotebookLanguage('mojo', nb);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBe('mod/back.py');
		nbmod.setNotebookLanguage('python', nb);
		expect(nbmod.getNotebook(nb).exportTarget).toBe('mod/back.py');
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBe('mod/back.mojo');
	});

	it('stops reporting it once the user deletes it - the remedy the sentence offers works', () => {
		const nb = exportingNotebook('gone.ipynb', 'mod/gone.py');
		nbmod.setNotebookLanguage('mojo', nb);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBe('mod/gone.py');
		rmSync(join(WS, 'mod/gone.py')); // exactly what the sentence tells the user to do
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBeNull();
	});
});

describe('PROVENANCE: only a module Cellar generated FROM THIS notebook is reported', () => {
	it('never names a HAND-WRITTEN module at the sibling path', () => {
		const nb = exportingNotebook('hand.ipynb', 'mod/hand.py');
		nbmod.setNotebookLanguage('mojo', nb);
		// The user's own source file, where a generated one used to be. Calling this a
		// stale Cellar module would invite deleting work Cellar never wrote.
		put('mod/hand.py', 'def hand_written():\n    return 1\n');
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBeNull();
	});

	it('never names a module ANOTHER notebook generated and still writes', () => {
		const nb = exportingNotebook('mine.ipynb', 'mod/shared.py');
		nbmod.setNotebookLanguage('mojo', nb);
		put('mod/shared.py', `${HEADER}\n# Source notebook: theirs.ipynb\n\ndef theirs():\n    return 2\n`);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBeNull();
	});

	it('names it when the header really records THIS notebook', () => {
		// The control for both refusals above: same shape, same path, only the recorded
		// source notebook differs - so they cannot pass by the check never firing.
		const nb = exportingNotebook('ours.ipynb', 'mod/ours.py');
		nbmod.setNotebookLanguage('mojo', nb);
		put('mod/ours.py', `${HEADER}\n# Source notebook: ours.ipynb\n\ndef ours():\n    return 3\n`);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBe('mod/ours.py');
	});
});

describe('COST: the check narrows before it touches the filesystem', () => {
	it('a notebook with NO export target opens no module at all', () => {
		const nb = nbmod.resolveNotebookPath('plain.ipynb');
		nbmod.createNotebook('plain.ipynb');
		nbmod.addCell(null, 'code', nb, null, 'x = 1');
		expect(moduleOpens(() => nbmod.getNotebook(nb))).toEqual([]);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBeNull();
	});

	it('a target naming NO module opens nothing either', () => {
		// `setExportTarget` refuses a non-module extension, so this shape only ever
		// arrives by HAND EDIT - written straight into the file the loader reads.
		put(
			'notes.ipynb',
			JSON.stringify({
				cells: [{ cell_type: 'code', id: 'c0', source: ['x = 1'], metadata: {}, outputs: [], execution_count: null }],
				metadata: { cellar: { export_target: 'notes.txt' } },
				nbformat: 4,
				nbformat_minor: 5
			})
		);
		const nb = nbmod.resolveNotebookPath('notes.ipynb');
		expect(moduleOpens(() => nbmod.getNotebook(nb))).toEqual([]);
		expect(nbmod.getNotebook(nb).exportOrphanedModule).toBeNull();
	});

	it('a target that DOES name a module opens exactly the one sibling', () => {
		// The mirror, so the two cases above cannot pass by the probe never running:
		// past the gate it is one bounded head read of one path.
		const nb = exportingNotebook('cost.ipynb', 'mod/cost.py');
		const probed = moduleOpens(() => nbmod.getNotebook(nb));
		expect(probed.filter((p) => p.endsWith('mod/cost.mojo'))).toHaveLength(1);
		expect(probed.filter((p) => p.endsWith('mod/cost.py'))).toEqual([]);
	});
});
